// Maps a listening_tracks id to a bundled local audio asset, generated by
// `npm run audio:generate` (scripts/generate-audio.ts) from a real TTS
// provider. Metro requires local asset paths to be static string literals,
// so this file is regenerated in full every time the script runs — it must
// only ever reference files that actually exist under assets/audio/.
//
// Empty by default: with no entries, every listening track falls back to
// on-device text-to-speech (still real, audible playback — see
// components/testing/TranscriptAudioPlayer.tsx) until real audio is
// generated for it.
export const audioRegistry: Record<string, number> = {};
