import type { GrammarQuestion } from '@/types/models';

/** `topic` matches a GrammarLesson.title exactly, so weak-topic detection
 * (services/repository/learning.ts#weakGrammarTopics) can recommend the
 * right lesson to review. Covers lessons g-15 through g-40 in lib/content/grammar.ts. */
export const grammarQuestions2: GrammarQuestion[] = [
  // Noun Clauses as Subjects and Objects
  {
    id: 'gq2-1', topic: 'Noun Clauses as Subjects and Objects', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Which sentence contains a noun clause functioning as the subject?',
    options: ['What surprised researchers was the speed of the change.', 'The researchers who studied the data were surprised.', 'Researchers were surprised by the speed of the change.', 'The speed of the change surprised researchers quickly.'],
    correctAnswer: 'What surprised researchers was the speed of the change.',
    explanation: 'The clause "What surprised researchers" functions as the subject of the verb "was", making it a noun clause rather than a relative or simple clause.',
    orderIndex: 1,
  },
  {
    id: 'gq2-2', topic: 'Noun Clauses as Subjects and Objects', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Complete: "Many economists believe ______ automation will reduce demand for low-skilled labour."',
    options: null, correctAnswer: 'that',
    explanation: '"That" introduces a noun clause acting as the object of "believe"; keeping it is more formal and precise in academic writing.',
    orderIndex: 2,
  },
  {
    id: 'gq2-3', topic: 'Noun Clauses as Subjects and Objects', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "The report shows what the recycling rates have doubled."',
    options: null, correctAnswer: 'The report shows that the recycling rates have doubled.',
    explanation: '"Show" needs a noun clause introduced by "that" to report a fact, not "what" — "what" would only be correct if the clause itself needed a missing object, which is not the case here.',
    orderIndex: 3,
  },
  {
    id: 'gq2-4', topic: 'Noun Clauses as Subjects and Objects', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence correctly uses a noun clause as the object of "know"?',
    options: ['I do not know why does the trend continue.', 'I do not know why the trend continues.', 'I do not know why is the trend continuing.', 'I do not know the trend why continues.'],
    correctAnswer: 'I do not know why the trend continues.',
    explanation: 'The noun clause after "know" uses normal statement word order (subject before verb), not question word order.',
    orderIndex: 4,
  },
  {
    id: 'gq2-5', topic: 'Noun Clauses as Subjects and Objects', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete: "______ the policy will succeed remains uncertain." (noun clause as subject, expressing doubt)',
    options: null, correctAnswer: 'Whether',
    explanation: '"Whether" introduces a noun clause expressing uncertainty and can act as the subject of the sentence, unlike "if", which is not normally used to open a subject clause.',
    orderIndex: 5,
  },

  // Adverb Clauses of Time, Reason, and Contrast
  {
    id: 'gq2-6', topic: 'Adverb Clauses of Time, Reason, and Contrast', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Which sentence correctly uses an adverb clause of contrast?',
    options: ['Whereas urban areas have grown, rural populations have declined.', 'Because urban areas have grown, rural populations have declined.', 'Urban areas have grown, so rural populations have declined.', 'Urban areas whereas have grown, rural populations have declined.'],
    correctAnswer: 'Whereas urban areas have grown, rural populations have declined.',
    explanation: '"Whereas" introduces an adverb clause of contrast between two facts, which fits the relationship between growing urban areas and declining rural ones.',
    orderIndex: 6,
  },
  {
    id: 'gq2-7', topic: 'Adverb Clauses of Time, Reason, and Contrast', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Complete: "______ the policy was unpopular, the council pressed ahead with it." (contrast)',
    options: null, correctAnswer: 'Even though',
    explanation: '"Even though" introduces an adverb clause of contrast, matching the logical relationship between unpopularity and pressing ahead.',
    orderIndex: 7,
  },
  {
    id: 'gq2-8', topic: 'Adverb Clauses of Time, Reason, and Contrast', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "As soon as, the meeting ended everyone left the room."',
    options: null, correctAnswer: 'As soon as the meeting ended, everyone left the room.',
    explanation: 'The comma belongs after the full adverb clause ("As soon as the meeting ended"), not immediately after the subordinator "As soon as".',
    orderIndex: 8,
  },
  {
    id: 'gq2-9', topic: 'Adverb Clauses of Time, Reason, and Contrast', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Choose the sentence where the adverb clause correctly gives a reason.',
    options: ['Since the data was incomplete, the study was delayed.', 'Since the study was delayed, incomplete the data was.', 'The data was incomplete since the study was delayed.', 'Since incomplete, the data delayed the study.'],
    correctAnswer: 'Since the data was incomplete, the study was delayed.',
    explanation: '"Since" here introduces a reason (the data being incomplete) for the result (the delayed study), correctly placed as a subordinate clause before the main clause.',
    orderIndex: 9,
  },
  {
    id: 'gq2-10', topic: 'Adverb Clauses of Time, Reason, and Contrast', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Complete: "Prices fell sharply ______ demand dropped unexpectedly." (reason)',
    options: null, correctAnswer: 'because',
    explanation: '"Because" directly introduces the reason for the price fall, fitting the cause-and-effect relationship in the sentence.',
    orderIndex: 10,
  },

  // Identifying and Fixing Sentence Fragments
  {
    id: 'gq2-11', topic: 'Identifying and Fixing Sentence Fragments', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Which of the following is a sentence fragment?',
    options: ['Because many people rely on cars for daily commuting.', 'Many people rely on cars for daily commuting.', 'Cars are relied on by many people daily.', 'Many people commute daily by car.'],
    correctAnswer: 'Because many people rely on cars for daily commuting.',
    explanation: 'This is a subordinate clause with no main clause attached, so it cannot stand alone as a complete sentence — it is a fragment.',
    orderIndex: 11,
  },
  {
    id: 'gq2-12', topic: 'Identifying and Fixing Sentence Fragments', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the fragment: "The government introduced new laws. Which many businesses opposed."',
    options: null, correctAnswer: 'The government introduced new laws, which many businesses opposed.',
    explanation: 'The fragment "Which many businesses opposed" must be joined to the previous sentence with a comma, since it is a relative clause, not an independent sentence.',
    orderIndex: 12,
  },
  {
    id: 'gq2-13', topic: 'Identifying and Fixing Sentence Fragments', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Fix the fragment by adding a subject and verb: "Although rising steadily since 2015." → "Although prices ______ rising steadily since 2015, wages have not kept pace."',
    options: null, correctAnswer: 'have been',
    explanation: 'The fragment lacked a subject and a complete verb; adding "prices have been" turns it into a valid subordinate clause attached to a main clause.',
    orderIndex: 13,
  },
  {
    id: 'gq2-14', topic: 'Identifying and Fixing Sentence Fragments', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence is a complete sentence, not a fragment?',
    options: ['When the economy slows down.', 'Slowing down significantly last year.', 'The economy slowed down significantly last year.', 'Because the economy, which slowed down.'],
    correctAnswer: 'The economy slowed down significantly last year.',
    explanation: 'This is the only option with a subject ("The economy") and a complete main verb ("slowed down") forming an independent clause.',
    orderIndex: 14,
  },
  {
    id: 'gq2-15', topic: 'Identifying and Fixing Sentence Fragments', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the fragment: "Many students prefer online courses. Since they offer more flexibility."',
    options: null, correctAnswer: 'Many students prefer online courses since they offer more flexibility.',
    explanation: 'The subordinate clause "Since they offer more flexibility" cannot stand alone and should be attached to the preceding independent clause.',
    orderIndex: 15,
  },

  // Run-on Sentences: Fusing Independent Clauses
  {
    id: 'gq2-16', topic: 'Run-on Sentences: Fusing Independent Clauses', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the run-on: "House prices rose sharply many families could no longer afford to buy."',
    options: null, correctAnswer: 'House prices rose sharply, so many families could no longer afford to buy.',
    explanation: 'Two independent clauses were fused with no punctuation at all; adding a comma and a coordinating conjunction ("so") correctly joins them.',
    orderIndex: 16,
  },
  {
    id: 'gq2-17', topic: 'Run-on Sentences: Fusing Independent Clauses', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence is a run-on sentence?',
    options: ['Traffic increased congestion worsened across the city.', 'Traffic increased, so congestion worsened across the city.', 'Traffic increased; congestion worsened across the city.', 'As traffic increased, congestion worsened across the city.'],
    correctAnswer: 'Traffic increased congestion worsened across the city.',
    explanation: 'This option fuses two independent clauses with no punctuation or conjunction between them, making it a run-on sentence.',
    orderIndex: 17,
  },
  {
    id: 'gq2-18', topic: 'Run-on Sentences: Fusing Independent Clauses', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Fix the run-on by adding correct punctuation: "The results were surprising___ few people had predicted them." (join with a semicolon)',
    options: null, correctAnswer: ';',
    explanation: 'A semicolon correctly joins two closely related independent clauses without needing a conjunction, fixing the run-on.',
    orderIndex: 18,
  },
  {
    id: 'gq2-19', topic: 'Run-on Sentences: Fusing Independent Clauses', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the run-on: "The plan was ambitious it lacked sufficient funding."',
    options: null, correctAnswer: 'The plan was ambitious, but it lacked sufficient funding.',
    explanation: 'The two independent clauses need a comma plus a coordinating conjunction such as "but" to be joined correctly, rather than being fused together.',
    orderIndex: 19,
  },
  {
    id: 'gq2-20', topic: 'Run-on Sentences: Fusing Independent Clauses', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which is the best way to fix "Costs rose demand fell sharply"?',
    options: ['Costs rose, demand fell sharply.', 'Costs rose. Demand fell sharply.', 'Costs rose demand, fell sharply.', 'Costs, rose demand fell sharply.'],
    correctAnswer: 'Costs rose. Demand fell sharply.',
    explanation: 'Splitting the fused independent clauses into two separate sentences correctly fixes the run-on, since a comma alone would only create a comma splice.',
    orderIndex: 20,
  },

  // Determiners: This/That/These/Those and Some/Any
  {
    id: 'gq2-21', topic: 'Determiners: This/That/These/Those and Some/Any', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Choose the correct sentence.',
    options: ['These policy has helped many families.', 'This policies has helped many families.', 'This policy has helped many families.', 'These policy have helped many families.'],
    correctAnswer: 'This policy has helped many families.',
    explanation: '"Policy" is singular, so it must be paired with the singular determiner "this", not the plural "these".',
    orderIndex: 21,
  },
  {
    id: 'gq2-22', topic: 'Determiners: This/That/These/Those and Some/Any', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Complete: "There isn\'t ______ evidence to support this claim."',
    options: null, correctAnswer: 'any',
    explanation: '"Any" is used in negative statements ("isn\'t any evidence"), while "some" is used mainly in positive statements and offers.',
    orderIndex: 22,
  },
  {
    id: 'gq2-23', topic: 'Determiners: This/That/These/Those and Some/Any', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "These results are surprising, and this findings support the theory."',
    options: null, correctAnswer: 'These results are surprising, and these findings support the theory.',
    explanation: '"Findings" is plural, so it must take the plural determiner "these" rather than the singular "this".',
    orderIndex: 23,
  },
  {
    id: 'gq2-24', topic: 'Determiners: This/That/These/Those and Some/Any', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence uses the most formal register for an IELTS Task 2 essay?',
    options: ['A lot of countries have banned plastic bags.', 'Lots of countries have banned plastic bags.', 'Many countries have banned plastic bags.', 'Tons of countries have banned plastic bags.'],
    correctAnswer: 'Many countries have banned plastic bags.',
    explanation: '"Many" is preferred over "a lot of"/"lots of"/"tons of" for a more formal academic register in Writing Task 2.',
    orderIndex: 24,
  },
  {
    id: 'gq2-25', topic: 'Determiners: This/That/These/Those and Some/Any', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Complete: "______ countries have introduced a carbon tax in recent years." (positive statement)',
    options: null, correctAnswer: 'Some',
    explanation: '"Some" is the natural choice for a positive statement about an unspecified quantity of countries.',
    orderIndex: 25,
  },

  // Countable vs Uncountable Nouns
  {
    id: 'gq2-26', topic: 'Countable vs Uncountable Nouns', difficulty: 'easy', questionType: 'error_correction',
    prompt: 'Find and correct the error: "The government needs more informations about public opinion."',
    options: null, correctAnswer: 'The government needs more information about public opinion.',
    explanation: '"Information" is an uncountable noun in English and has no plural form, so "informations" is incorrect.',
    orderIndex: 26,
  },
  {
    id: 'gq2-27', topic: 'Countable vs Uncountable Nouns', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Choose the correct sentence.',
    options: ['Many evidences suggest a link between diet and health.', 'Much evidence suggests a link between diet and health.', 'Much evidences suggests a link between diet and health.', 'Many evidence suggest a link between diet and health.'],
    correctAnswer: 'Much evidence suggests a link between diet and health.',
    explanation: '"Evidence" is uncountable, so it pairs with "much" (not "many") and takes a singular verb ("suggests").',
    orderIndex: 27,
  },
  {
    id: 'gq2-28', topic: 'Countable vs Uncountable Nouns', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete: "She gave me a useful ______ of advice before the interview." (quantifying phrase)',
    options: null, correctAnswer: 'piece',
    explanation: '"Advice" is uncountable, so it must be quantified with a phrase like "a piece of advice" rather than "an advice".',
    orderIndex: 28,
  },
  {
    id: 'gq2-29', topic: 'Countable vs Uncountable Nouns', difficulty: 'medium', questionType: 'error_correction',
    prompt: 'Find and correct the error: "The company bought new equipments for the factory."',
    options: null, correctAnswer: 'The company bought new equipment for the factory.',
    explanation: '"Equipment" is uncountable and has no plural form; "equipments" is a common but incorrect form.',
    orderIndex: 29,
  },
  {
    id: 'gq2-30', topic: 'Countable vs Uncountable Nouns', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Which sentence is grammatically correct?',
    options: ['There is little research on this topic.', 'There is few research on this topic.', 'There are little researches on this topic.', 'There is a few research on this topic.'],
    correctAnswer: 'There is little research on this topic.',
    explanation: '"Research" is uncountable, so it takes "little" (not "few") and a singular verb ("is").',
    orderIndex: 30,
  },

  // Gerunds vs Infinitives After Verbs
  {
    id: 'gq2-31', topic: 'Gerunds vs Infinitives After Verbs', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Choose the correct sentence.',
    options: ['The report suggests to invest in renewable energy.', 'The report suggests investing in renewable energy.', 'The report suggests invest in renewable energy.', 'The report suggests to investing in renewable energy.'],
    correctAnswer: 'The report suggests investing in renewable energy.',
    explanation: '"Suggest" is always followed by a gerund (-ing form) or a that-clause, never a bare to-infinitive.',
    orderIndex: 31,
  },
  {
    id: 'gq2-32', topic: 'Gerunds vs Infinitives After Verbs', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Complete: "The company has decided ______ (expand) into new markets next year."',
    options: null, correctAnswer: 'to expand',
    explanation: '"Decide" is followed by a to-infinitive, so "to expand" is the correct form here.',
    orderIndex: 32,
  },
  {
    id: 'gq2-33', topic: 'Gerunds vs Infinitives After Verbs', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "The committee avoided to discuss the controversial issue."',
    options: null, correctAnswer: 'The committee avoided discussing the controversial issue.',
    explanation: '"Avoid" is always followed by a gerund, not a to-infinitive, so "discussing" is required rather than "to discuss".',
    orderIndex: 33,
  },
  {
    id: 'gq2-34', topic: 'Gerunds vs Infinitives After Verbs', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence correctly shows the meaning "he quit the habit of smoking"?',
    options: ['He stopped to smoke.', 'He stopped smoking.', 'He stopped smoke.', 'He stopped for smoking.'],
    correctAnswer: 'He stopped smoking.',
    explanation: '"Stop + gerund" means to quit an activity, while "stop + to-infinitive" means pausing another activity in order to do something.',
    orderIndex: 34,
  },
  {
    id: 'gq2-35', topic: 'Gerunds vs Infinitives After Verbs', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Complete: "Many students enjoy ______ (study) in groups rather than alone."',
    options: null, correctAnswer: 'studying',
    explanation: '"Enjoy" is always followed by a gerund, so "studying" is the correct form.',
    orderIndex: 35,
  },

  // Participle Clauses Replacing Relative Clauses
  {
    id: 'gq2-36', topic: 'Participle Clauses Replacing Relative Clauses', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence correctly uses an -ing participle clause?',
    options: ['Students studying abroad often gain confidence.', 'Students studied abroad often gain confidence.', 'Students who studying abroad often gain confidence.', 'Students study abroad often gain confidence.'],
    correctAnswer: 'Students studying abroad often gain confidence.',
    explanation: 'The -ing participle clause "studying abroad" replaces the relative clause "who study abroad" without needing a relative pronoun.',
    orderIndex: 36,
  },
  {
    id: 'gq2-37', topic: 'Participle Clauses Replacing Relative Clauses', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "The data collecting in 2020 shows a sharp rise."',
    options: null, correctAnswer: 'The data collected in 2020 shows a sharp rise.',
    explanation: 'Since the data was collected by someone else (passive meaning), the past participle "collected" is required, not the present participle "collecting".',
    orderIndex: 37,
  },
  {
    id: 'gq2-38', topic: 'Participle Clauses Replacing Relative Clauses', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Rewrite using a participle clause: "The report that was published last year" → "The report ______ last year"',
    options: null, correctAnswer: 'published',
    explanation: 'A past participle clause ("published last year") replaces the passive relative clause "that was published last year".',
    orderIndex: 38,
  },
  {
    id: 'gq2-39', topic: 'Participle Clauses Replacing Relative Clauses', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Which participle clause correctly replaces "who work in the city centre"?',
    options: ['Working in the city centre', 'Worked in the city centre', 'To work in the city centre', 'Works in the city centre'],
    correctAnswer: 'Working in the city centre',
    explanation: 'Because the verb in the original clause is active ("work"), the -ing participle form "working" is used to replace it.',
    orderIndex: 39,
  },
  {
    id: 'gq2-40', topic: 'Participle Clauses Replacing Relative Clauses', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "The bridge damaging by the storm was closed for repairs."',
    options: null, correctAnswer: 'The bridge damaged by the storm was closed for repairs.',
    explanation: 'The bridge did not damage something — it was damaged, so the passive past participle "damaged" is needed instead of "damaging".',
    orderIndex: 40,
  },

  // Cleft Sentences for Emphasis
  {
    id: 'gq2-41', topic: 'Cleft Sentences for Emphasis', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which is the correct it-cleft version of "Cost drives most consumer decisions"?',
    options: ['It is cost that drives most consumer decisions.', 'It is cost drives most consumer decisions.', 'Cost is it that drives most consumer decisions.', 'It cost that drives most consumer decisions.'],
    correctAnswer: 'It is cost that drives most consumer decisions.',
    explanation: 'The it-cleft structure "It is/was + emphasised element + that..." correctly places "cost" in focus with "that" introducing the rest of the clause.',
    orderIndex: 41,
  },
  {
    id: 'gq2-42', topic: 'Cleft Sentences for Emphasis', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete the what-cleft: "______ governments need to do is invest in clean energy."',
    options: null, correctAnswer: 'What',
    explanation: 'A what-cleft begins with "What" to form a noun clause subject, emphasising the action that follows ("invest in clean energy").',
    orderIndex: 42,
  },
  {
    id: 'gq2-43', topic: 'Cleft Sentences for Emphasis', difficulty: 'medium', questionType: 'error_correction',
    prompt: 'Find and correct the error: "It is education that determine long-term social mobility."',
    options: null, correctAnswer: 'It is education that determines long-term social mobility.',
    explanation: 'The verb in the "that" clause must agree with the emphasised singular subject "education", so "determines" is required, not "determine".',
    orderIndex: 43,
  },
  {
    id: 'gq2-44', topic: 'Cleft Sentences for Emphasis', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Which sentence uses a what-cleft to emphasise an idea?',
    options: ['What concerns me most is the rising cost of housing.', 'What concerns me most rising cost of housing.', 'The rising cost of housing what concerns me most.', 'It concerns me what the rising cost of housing.'],
    correctAnswer: 'What concerns me most is the rising cost of housing.',
    explanation: 'This correctly uses "What concerns me most" as the subject noun clause, followed by "is" and the emphasised information.',
    orderIndex: 44,
  },
  {
    id: 'gq2-45', topic: 'Cleft Sentences for Emphasis', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete the it-cleft: "It was the lack of funding ______ caused the project to fail."',
    options: null, correctAnswer: 'that',
    explanation: '"That" (or "which") introduces the remainder of the it-cleft clause after the emphasised element "the lack of funding".',
    orderIndex: 45,
  },

  // Inversion After Negative Adverbials
  {
    id: 'gq2-46', topic: 'Inversion After Negative Adverbials', difficulty: 'hard', questionType: 'multiple_choice',
    prompt: 'Which sentence correctly uses inversion after a negative adverbial?',
    options: ['Never has the issue been more urgent.', 'Never the issue has been more urgent.', 'Never the issue been has more urgent.', 'The issue never has been more urgent.'],
    correctAnswer: 'Never has the issue been more urgent.',
    explanation: 'When "never" opens the sentence, the auxiliary verb inverts with the subject, producing "has the issue" rather than normal statement order.',
    orderIndex: 46,
  },
  {
    id: 'gq2-47', topic: 'Inversion After Negative Adverbials', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Complete with inversion: "Not only ______ the policy fail, but it also increased costs."',
    options: null, correctAnswer: 'did',
    explanation: '"Not only" at the start of a sentence triggers inversion, requiring the auxiliary "did" before the subject "the policy".',
    orderIndex: 47,
  },
  {
    id: 'gq2-48', topic: 'Inversion After Negative Adverbials', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "Rarely a solution works so effectively across every region."',
    options: null, correctAnswer: 'Rarely does a solution work so effectively across every region.',
    explanation: 'The negative adverbial "Rarely" at the start of the sentence requires inversion with an auxiliary verb ("does"), not normal statement word order.',
    orderIndex: 48,
  },
  {
    id: 'gq2-49', topic: 'Inversion After Negative Adverbials', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence is grammatically correct and avoids inversion entirely?',
    options: ['The issue has never been more urgent.', 'Never the issue has been more urgent.', 'Has never the issue been more urgent.', 'Never has been the issue more urgent.'],
    correctAnswer: 'The issue has never been more urgent.',
    explanation: 'Placing "never" mid-sentence (not at the start) avoids the need for inversion, keeping normal subject-verb word order.',
    orderIndex: 49,
  },
  {
    id: 'gq2-50', topic: 'Inversion After Negative Adverbials', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete with the correct inverted form: "Under no circumstances ______ this data be shared without consent."',
    options: null, correctAnswer: 'should',
    explanation: 'The negative adverbial "Under no circumstances" requires inversion with a modal auxiliary such as "should" before the subject "this data".',
    orderIndex: 50,
  },

  // Present Perfect vs Past Simple
  {
    id: 'gq2-51', topic: 'Present Perfect vs Past Simple', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Which sentence is correct?',
    options: ['The population grew by 12% in 2015.', 'The population has grown by 12% in 2015.', 'The population has grew by 12% in 2015.', 'The population growing by 12% in 2015.'],
    correctAnswer: 'The population grew by 12% in 2015.',
    explanation: 'Because "in 2015" names a finished time, the past simple ("grew") is required, not the present perfect.',
    orderIndex: 51,
  },
  {
    id: 'gq2-52', topic: 'Present Perfect vs Past Simple', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Complete: "House prices ______ (rise) steadily since 2018." (trend continuing to now)',
    options: null, correctAnswer: 'have risen',
    explanation: 'The present perfect ("have risen") is used with "since" to describe a trend that started in the past and continues to the present.',
    orderIndex: 52,
  },
  {
    id: 'gq2-53', topic: 'Present Perfect vs Past Simple', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "The city has built the new stadium in 2019."',
    options: null, correctAnswer: 'The city built the new stadium in 2019.',
    explanation: '"In 2019" names a specific, finished time, so the past simple ("built") is required rather than the present perfect.',
    orderIndex: 53,
  },
  {
    id: 'gq2-54', topic: 'Present Perfect vs Past Simple', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence correctly describes an unfinished period up to now?',
    options: ['She has lived in this city for ten years.', 'She lived in this city for ten years.', 'She living in this city for ten years.', 'She has live in this city for ten years.'],
    correctAnswer: 'She has lived in this city for ten years.',
    explanation: 'Present perfect with "for" describes a duration that continues up to the present, which matches an unfinished ten-year period.',
    orderIndex: 54,
  },
  {
    id: 'gq2-55', topic: 'Present Perfect vs Past Simple', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete: "Unemployment ______ (fall) sharply last year." (specific finished time)',
    options: null, correctAnswer: 'fell',
    explanation: '"Last year" names a specific, finished time period, so the past simple ("fell") must be used rather than the present perfect.',
    orderIndex: 55,
  },

  // Future Forms: Will, Going To, and Present Continuous
  {
    id: 'gq2-56', topic: 'Future Forms: Will, Going To, and Present Continuous', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence best expresses a prediction based on current evidence?',
    options: ['Unemployment will rise.', 'Unemployment is going to rise because factories are already closing.', 'Unemployment rises because factories are already closing.', 'Unemployment rose because factories are already closing.'],
    correctAnswer: 'Unemployment is going to rise because factories are already closing.',
    explanation: '"Going to" is used for predictions based on present evidence, which matches the visible sign of factories already closing.',
    orderIndex: 56,
  },
  {
    id: 'gq2-57', topic: 'Future Forms: Will, Going To, and Present Continuous', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Complete: "I ______ (move) to a new apartment next month." (fixed, already-arranged plan)',
    options: null, correctAnswer: 'am moving',
    explanation: 'The present continuous describes a fixed, already-arranged future plan, which fits a personal arrangement like moving apartments.',
    orderIndex: 57,
  },
  {
    id: 'gq2-58', topic: 'Future Forms: Will, Going To, and Present Continuous', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "I move to a new apartment next month, it is already arranged."',
    options: null, correctAnswer: 'I am moving to a new apartment next month, it is already arranged.',
    explanation: 'Present simple sounds like a routine or timetable; a personal, already-arranged plan needs the present continuous ("am moving").',
    orderIndex: 58,
  },
  {
    id: 'gq2-59', topic: 'Future Forms: Will, Going To, and Present Continuous', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence correctly describes a scheduled, timetabled event?',
    options: ['The exam starts at 9 a.m.', 'The exam is going to start at 9 a.m. tomorrow only.', 'The exam will starting at 9 a.m.', 'The exam starting at 9 a.m.'],
    correctAnswer: 'The exam starts at 9 a.m.',
    explanation: 'Present simple is used for the future when describing fixed timetables or schedules, such as an exam start time.',
    orderIndex: 59,
  },
  {
    id: 'gq2-60', topic: 'Future Forms: Will, Going To, and Present Continuous', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Complete: "I think this trend ______ (continue) for the next few years." (general prediction/opinion)',
    options: null, correctAnswer: 'will continue',
    explanation: '"Will" is the natural choice for a general prediction or opinion about the future, made without pointing to specific present evidence.',
    orderIndex: 60,
  },

  // Quantifiers and Verb Agreement
  {
    id: 'gq2-61', topic: 'Quantifiers and Verb Agreement', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Choose the correct sentence.',
    options: ['Much solutions have been proposed.', 'Many solutions have been proposed.', 'Many solution have been proposed.', 'Much solution has been proposed.'],
    correctAnswer: 'Many solutions have been proposed.',
    explanation: '"Solutions" is countable and plural, so it takes "many" and the plural verb "have", not "much".',
    orderIndex: 61,
  },
  {
    id: 'gq2-62', topic: 'Quantifiers and Verb Agreement', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete: "Most of the evidence ______ (support) this view." (uncountable noun)',
    options: null, correctAnswer: 'supports',
    explanation: 'The verb after "most of" agrees with the noun that follows ("evidence", uncountable and singular), so "supports" is correct.',
    orderIndex: 62,
  },
  {
    id: 'gq2-63', topic: 'Quantifiers and Verb Agreement', difficulty: 'easy', questionType: 'error_correction',
    prompt: 'Find and correct the error: "Few people is aware of the risks involved."',
    options: null, correctAnswer: 'Few people are aware of the risks involved.',
    explanation: '"Few" pairs with a countable plural noun ("people"), which takes the plural verb "are", not "is".',
    orderIndex: 63,
  },
  {
    id: 'gq2-64', topic: 'Quantifiers and Verb Agreement', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Choose the correct sentence.',
    options: ['Most of the studies support this view.', 'Most of the studies supports this view.', 'Most of the study support this view.', 'Most of the studies is supporting this view.'],
    correctAnswer: 'Most of the studies support this view.',
    explanation: '"Studies" is plural, so the verb after "most of the studies" must also be plural ("support").',
    orderIndex: 64,
  },
  {
    id: 'gq2-65', topic: 'Quantifiers and Verb Agreement', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete: "______ debate surrounds this controversial policy." (uncountable noun quantifier)',
    options: null, correctAnswer: 'Much',
    explanation: '"Debate" is uncountable here, so it pairs with "much" rather than "many", which would require a plural countable noun.',
    orderIndex: 65,
  },

  // Apostrophes: Possession vs Contraction
  {
    id: 'gq2-66', topic: 'Apostrophes: Possession vs Contraction', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Choose the correctly punctuated sentence.',
    options: ['The governments policy was widely criticised.', 'The government\'s policy was widely criticised.', 'The governments\' policy was widely criticised.', 'The governments policy\'s was widely criticised.'],
    correctAnswer: 'The government\'s policy was widely criticised.',
    explanation: '"Government" is a singular noun, so possession is shown with an apostrophe plus "s" ("government\'s"), not an apostrophe after the "s" or no apostrophe at all.',
    orderIndex: 66,
  },
  {
    id: 'gq2-67', topic: 'Apostrophes: Possession vs Contraction', difficulty: 'medium', questionType: 'error_correction',
    prompt: 'Find and correct the error: "The companys profits increased its shareholders were pleased."',
    options: null, correctAnswer: 'The company\'s profits increased; its shareholders were pleased.',
    explanation: '"Company" needs a possessive apostrophe ("company\'s"), and the two independent clauses need a semicolon rather than being run together.',
    orderIndex: 67,
  },
  {
    id: 'gq2-68', topic: 'Apostrophes: Possession vs Contraction', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete with the correct possessive form (plural noun already ending in s): "The ______ results were announced yesterday." (belonging to the students)',
    options: null, correctAnswer: 'students\'',
    explanation: 'A plural noun already ending in "s" ("students") only needs an apostrophe after the "s" to show possession, not an additional "s".',
    orderIndex: 68,
  },
  {
    id: 'gq2-69', topic: 'Apostrophes: Possession vs Contraction', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence correctly distinguishes "its" from "it\'s"?',
    options: ['The company increased its profits this year.', 'The company increased it\'s profits this year.', 'The company increased its\' profits this year.', 'The company increased it is profits this year.'],
    correctAnswer: 'The company increased its profits this year.',
    explanation: '"Its" (no apostrophe) is the possessive form of "it"; "it\'s" is only correct as a contraction of "it is" or "it has".',
    orderIndex: 69,
  },
  {
    id: 'gq2-70', topic: 'Apostrophes: Possession vs Contraction', difficulty: 'easy', questionType: 'error_correction',
    prompt: 'Find and correct the error: "Its a common misconception that recycling always saves money."',
    options: null, correctAnswer: 'It\'s a common misconception that recycling always saves money.',
    explanation: 'The sentence needs the contraction "it\'s" (meaning "it is"), not the possessive "its", since no noun follows to be possessed.',
    orderIndex: 70,
  },

  // Hyphenation in Compound Adjectives
  {
    id: 'gq2-71', topic: 'Hyphenation in Compound Adjectives', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Choose the correctly hyphenated sentence.',
    options: ['This is a well known problem in urban planning.', 'This is a well-known problem in urban planning.', 'This is a well-known-problem in urban planning.', 'This is a well, known problem in urban planning.'],
    correctAnswer: 'This is a well-known problem in urban planning.',
    explanation: 'The compound adjective "well-known" modifying the noun "problem" before it is hyphenated.',
    orderIndex: 71,
  },
  {
    id: 'gq2-72', topic: 'Hyphenation in Compound Adjectives', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "The city needs a highly-effective transport strategy."',
    options: null, correctAnswer: 'The city needs a highly effective transport strategy.',
    explanation: 'Adverbs ending in -ly, such as "highly", are never hyphenated before the adjective they modify.',
    orderIndex: 72,
  },
  {
    id: 'gq2-73', topic: 'Hyphenation in Compound Adjectives', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Complete: "The council approved a five______year plan for the region." (compound adjective before a noun)',
    options: null, correctAnswer: '-',
    explanation: 'A number-plus-noun compound modifying a following noun ("five-year plan") is hyphenated.',
    orderIndex: 73,
  },
  {
    id: 'gq2-74', topic: 'Hyphenation in Compound Adjectives', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence correctly drops the hyphen because the compound comes after the noun?',
    options: ['The solution is long-term.', 'The solution is long term.', 'The long term solution.', 'The solution-is long term.'],
    correctAnswer: 'The solution is long term.',
    explanation: 'When "long term" comes after the noun it describes (as a complement, not a pre-noun modifier), it is usually written without a hyphen.',
    orderIndex: 74,
  },
  {
    id: 'gq2-75', topic: 'Hyphenation in Compound Adjectives', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Complete: "The report describes a 20______year______old building in need of repair." (compound adjective before a noun)',
    options: null, correctAnswer: '-, -',
    explanation: 'A number + noun + adjective compound modifying a noun before it ("20-year-old building") is hyphenated throughout.',
    orderIndex: 75,
  },

  // Collocation Errors with Make and Do
  {
    id: 'gq2-76', topic: 'Collocation Errors with Make and Do', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Choose the correct sentence.',
    options: ['She made a mistake on the form.', 'She did a mistake on the form.', 'She made mistake on the form.', 'She done a mistake on the form.'],
    correctAnswer: 'She made a mistake on the form.',
    explanation: '"Make a mistake" is the correct fixed collocation; "do a mistake" is a common but incorrect form.',
    orderIndex: 76,
  },
  {
    id: 'gq2-77', topic: 'Collocation Errors with Make and Do', difficulty: 'medium', questionType: 'error_correction',
    prompt: 'Find and correct the error: "The university encourages students to make research before choosing a topic."',
    options: null, correctAnswer: 'The university encourages students to do research before choosing a topic.',
    explanation: '"Do research" is the correct collocation, as research is an activity, not something created or produced in the sense "make" implies.',
    orderIndex: 77,
  },
  {
    id: 'gq2-78', topic: 'Collocation Errors with Make and Do', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete: "The new policy is expected to ______ a significant difference to local employment."',
    options: null, correctAnswer: 'make',
    explanation: '"Make a difference" is the correct fixed collocation, not "do a difference".',
    orderIndex: 78,
  },
  {
    id: 'gq2-79', topic: 'Collocation Errors with Make and Do', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence correctly uses "do"?',
    options: ['He does his homework every evening.', 'He makes his homework every evening.', 'He does a homework every evening.', 'He makes homework every evening.'],
    correctAnswer: 'He does his homework every evening.',
    explanation: '"Do homework" is the correct fixed collocation for this everyday duty/activity.',
    orderIndex: 79,
  },
  {
    id: 'gq2-80', topic: 'Collocation Errors with Make and Do', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Complete: "The factory\'s emissions ______ considerable damage to the local environment."',
    options: null, correctAnswer: 'do',
    explanation: '"Do damage" (or "cause damage") is the correct collocation; "make damage" is incorrect.',
    orderIndex: 80,
  },

  // Phrasal Verbs in Formal Academic Writing
  {
    id: 'gq2-81', topic: 'Phrasal Verbs in Formal Academic Writing', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence is more appropriate for formal Task 2 writing?',
    options: ['The committee will look into the matter further.', 'The committee will investigate the matter further.', 'The committee will look the matter into further.', 'The committee will look into further the matter.'],
    correctAnswer: 'The committee will investigate the matter further.',
    explanation: '"Investigate" is a single-word, more formal equivalent of the phrasal verb "look into", which suits academic register better.',
    orderIndex: 81,
  },
  {
    id: 'gq2-82', topic: 'Phrasal Verbs in Formal Academic Writing', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Rewrite formally: "The government should come up with a solution." → "The government should ______ a solution." (formal single-word equivalent)',
    options: null, correctAnswer: 'devise',
    explanation: '"Devise" or "propose" is a more formal single-word alternative to the phrasal verb "come up with".',
    orderIndex: 82,
  },
  {
    id: 'gq2-83', topic: 'Phrasal Verbs in Formal Academic Writing', difficulty: 'medium', questionType: 'error_correction',
    prompt: 'Rewrite more formally: "We need to get rid of outdated regulations."',
    options: null, correctAnswer: 'We need to eliminate outdated regulations.',
    explanation: '"Eliminate" is a formal single-word substitute for the phrasal verb "get rid of", better suited to academic Writing Task 2.',
    orderIndex: 83,
  },
  {
    id: 'gq2-84', topic: 'Phrasal Verbs in Formal Academic Writing', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'In which context are phrasal verbs generally most appropriate?',
    options: ['A formal Writing Task 2 essay', 'An academic Task 1 report', 'A natural Speaking Part 1 answer', 'A formal cover letter'],
    correctAnswer: 'A natural Speaking Part 1 answer',
    explanation: 'Phrasal verbs sound natural and conversational, which fits the informal, spoken register expected in Speaking Part 1.',
    orderIndex: 84,
  },
  {
    id: 'gq2-85', topic: 'Phrasal Verbs in Formal Academic Writing', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Rewrite formally: "The meeting was put off until next week." → "The meeting was ______ until next week."',
    options: null, correctAnswer: 'postponed',
    explanation: '"Postponed" is the formal single-word equivalent of the phrasal verb "put off".',
    orderIndex: 85,
  },

  // Academic Word Choice: Formal vs Informal Register
  {
    id: 'gq2-86', topic: 'Academic Word Choice: Formal vs Informal Register', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Which sentence is most appropriate for formal Task 2 writing?',
    options: ['A lot of kids struggle with big changes in schooling.', 'Many children struggle with significant changes in schooling.', 'Lots of kids struggle with huge changes in schooling.', 'Tons of kids struggle with massive changes in schooling.'],
    correctAnswer: 'Many children struggle with significant changes in schooling.',
    explanation: '"Many" and "children" and "significant" are more formal academic alternatives to "a lot of", "kids", and "big/huge".',
    orderIndex: 86,
  },
  {
    id: 'gq2-87', topic: 'Academic Word Choice: Formal vs Informal Register', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Rewrite formally: "The company needs to get more customers." → "The company needs to ______ more customers."',
    options: null, correctAnswer: 'obtain',
    explanation: '"Obtain" is a more formal alternative to the informal verb "get" in this context.',
    orderIndex: 87,
  },
  {
    id: 'gq2-88', topic: 'Academic Word Choice: Formal vs Informal Register', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Rewrite more formally: "There is a lot of stuff we could do to fix this problem."',
    options: null, correctAnswer: 'There are several measures that could be taken to address this problem.',
    explanation: '"Stuff", "a lot of", and "fix" are informal; replacing them with "several measures", and "address" produces a more academic register.',
    orderIndex: 88,
  },
  {
    id: 'gq2-89', topic: 'Academic Word Choice: Formal vs Informal Register', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which linking choice is more formal?',
    options: ['But the results varied by region.', 'However, the results varied by region.', 'Plus, the results varied by region.', 'So, the results varied by region, right?'],
    correctAnswer: 'However, the results varied by region.',
    explanation: '"However" is a more formal linking adverb than "but", "plus", or a casual tag like "right?".',
    orderIndex: 89,
  },
  {
    id: 'gq2-90', topic: 'Academic Word Choice: Formal vs Informal Register', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Rewrite formally: "This is a big issue for developing countries." → "This is a ______ issue for developing countries."',
    options: null, correctAnswer: 'significant',
    explanation: '"Significant" or "considerable" is a more formal alternative to the informal adjective "big".',
    orderIndex: 90,
  },

  // Avoiding Redundancy and Wordiness
  {
    id: 'gq2-91', topic: 'Avoiding Redundancy and Wordiness', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence avoids redundancy?',
    options: ['We must completely eliminate each and every basic fundamental problem.', 'We must eliminate every fundamental problem.', 'We must completely eliminate every basic problem completely.', 'We must each and every eliminate fundamental problem.'],
    correctAnswer: 'We must eliminate every fundamental problem.',
    explanation: '"Eliminate" already means to remove completely, and "fundamental" alone conveys the core meaning, so "completely eliminate" and "basic fundamental" are redundant.',
    orderIndex: 91,
  },
  {
    id: 'gq2-92', topic: 'Avoiding Redundancy and Wordiness', difficulty: 'easy', questionType: 'error_correction',
    prompt: 'Rewrite to remove redundancy: "The final outcome of the study confirmed the hypothesis."',
    options: null, correctAnswer: 'The outcome of the study confirmed the hypothesis.',
    explanation: '"Outcome" already implies a final result, so "final" is redundant and can be removed.',
    orderIndex: 92,
  },
  {
    id: 'gq2-93', topic: 'Avoiding Redundancy and Wordiness', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Rewrite concisely: "Due to the fact that costs rose, demand fell." → "______ costs rose, demand fell."',
    options: null, correctAnswer: 'Because',
    explanation: '"Because" is a concise one-word replacement for the wordy phrase "due to the fact that".',
    orderIndex: 93,
  },
  {
    id: 'gq2-94', topic: 'Avoiding Redundancy and Wordiness', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which phrase is the most concise replacement for "a large number of"?',
    options: ['many', 'a big amount of', 'quite a lot of', 'a huge quantity of'],
    correctAnswer: 'many',
    explanation: '"Many" is the single-word, concise replacement for the wordy phrase "a large number of".',
    orderIndex: 94,
  },
  {
    id: 'gq2-95', topic: 'Avoiding Redundancy and Wordiness', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Rewrite to remove redundancy: "In my future plans, I hope to study abroad."',
    options: null, correctAnswer: 'In my plans, I hope to study abroad.',
    explanation: '"Plans" are inherently about the future, so "future plans" is redundant; "plans" alone is sufficient.',
    orderIndex: 95,
  },

  // Sentence Variety: Varying Sentence Openers
  {
    id: 'gq2-96', topic: 'Sentence Variety: Varying Sentence Openers', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence opens with a prepositional phrase instead of the grammatical subject?',
    options: ['Healthcare access remains limited in many developing countries.', 'In many developing countries, access to healthcare remains limited.', 'Access to healthcare, in many developing countries, remains limited.', 'It remains limited, access to healthcare in developing countries.'],
    correctAnswer: 'In many developing countries, access to healthcare remains limited.',
    explanation: 'This sentence opens with the prepositional phrase "In many developing countries" rather than starting directly with the subject "access".',
    orderIndex: 96,
  },
  {
    id: 'gq2-97', topic: 'Sentence Variety: Varying Sentence Openers', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete with a participle clause opener: "______ with rising costs, many families cut back on spending."',
    options: null, correctAnswer: 'Faced',
    explanation: '"Faced with rising costs" is a past participle clause opener that varies the sentence structure instead of starting with the subject.',
    orderIndex: 97,
  },
  {
    id: 'gq2-98', topic: 'Sentence Variety: Varying Sentence Openers', difficulty: 'medium', questionType: 'error_correction',
    prompt: 'Improve variety by rewriting with an adverb clause opener: "The policy proved effective. The policy was controversial." (combine using although, opener first)',
    options: null, correctAnswer: 'Although the policy was controversial, it proved effective.',
    explanation: 'Opening with the adverb clause "Although the policy was controversial" varies the sentence structure while combining the two ideas logically.',
    orderIndex: 98,
  },
  {
    id: 'gq2-99', topic: 'Sentence Variety: Varying Sentence Openers', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Which paragraph shows the least sentence variety?',
    options: ['The government acted quickly. The economy responded well. The public remained cautious.', 'Acting quickly, the government stabilised the economy, and the public remained cautious.', 'Although the government acted quickly, the public remained cautious.', 'Despite quick government action, the public remained cautious.'],
    correctAnswer: 'The government acted quickly. The economy responded well. The public remained cautious.',
    explanation: 'All three sentences here begin directly with their grammatical subject, producing a repetitive, mechanical rhythm.',
    orderIndex: 99,
  },
  {
    id: 'gq2-100', topic: 'Sentence Variety: Varying Sentence Openers', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Complete with an adverb clause opener: "______ the exam was difficult, most students passed." (contrast)',
    options: null, correctAnswer: 'Although',
    explanation: '"Although" opens the sentence with a subordinate clause of contrast, varying the sentence structure instead of starting with the subject.',
    orderIndex: 100,
  },

  // Cohesive Reference: This, That, These, It
  {
    id: 'gq2-101', topic: 'Cohesive Reference: This, That, These, It', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Which sentence uses cohesive reference correctly?',
    options: ['Recycling rates have doubled. This trend is likely to continue.', 'Recycling rates have doubled. Trend is likely to continue.', 'Recycling rates have doubled. That trend likely continue.', 'Recycling rates have doubled. This trends is likely to continue.'],
    correctAnswer: 'Recycling rates have doubled. This trend is likely to continue.',
    explanation: '"This trend" clearly and grammatically refers back to the idea of doubled recycling rates mentioned in the previous sentence.',
    orderIndex: 101,
  },
  {
    id: 'gq2-102', topic: 'Cohesive Reference: This, That, These, It', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Improve clarity: "The report criticised the policy and praised the team. This shows real progress was made."',
    options: null, correctAnswer: 'The report criticised the policy and praised the team. This praise shows real progress was made.',
    explanation: 'The original "this" was ambiguous, since it could refer to the criticism, the praise, or both — adding the noun "praise" removes the ambiguity.',
    orderIndex: 102,
  },
  {
    id: 'gq2-103', topic: 'Cohesive Reference: This, That, These, It', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Complete for clear cohesive reference: "The city introduced new cycle lanes. ______ measure has reduced traffic significantly."',
    options: null, correctAnswer: 'This',
    explanation: '"This measure" clearly refers back to the cycle lanes mentioned in the previous sentence, with the added noun avoiding ambiguity.',
    orderIndex: 103,
  },
  {
    id: 'gq2-104', topic: 'Cohesive Reference: This, That, These, It', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence avoids vague reference?',
    options: ['The team missed the deadline and lost the client. This was unfortunate.', 'The team missed the deadline and lost the client. This delay was unfortunate.', 'The team missed the deadline and lost the client. It unfortunate.', 'The team missed the deadline and lost the client. That were unfortunate.'],
    correctAnswer: 'The team missed the deadline and lost the client. This delay was unfortunate.',
    explanation: 'Adding the noun "delay" after "this" makes clear exactly which of the two events is being referred to, avoiding ambiguity.',
    orderIndex: 104,
  },
  {
    id: 'gq2-105', topic: 'Cohesive Reference: This, That, These, It', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Complete: "Several new laws were passed last year. ______ have already had a visible effect." (plural reference)',
    options: null, correctAnswer: 'These',
    explanation: '"These" correctly refers back to the plural noun "laws" mentioned in the previous sentence.',
    orderIndex: 105,
  },

  // Ellipsis: Omitting Repeated Words
  {
    id: 'gq2-106', topic: 'Ellipsis: Omitting Repeated Words', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence correctly uses ellipsis?',
    options: ['Some students prefer online classes, and others prefer traditional ones.', 'Some students prefer online classes, and others traditional ones.', 'Some students prefer online classes, and others.', 'Some students prefer online classes, and others prefer.'],
    correctAnswer: 'Some students prefer online classes, and others traditional ones.',
    explanation: 'The repeated verb "prefer" is correctly omitted in the second clause because it is clearly understood from context.',
    orderIndex: 106,
  },
  {
    id: 'gq2-107', topic: 'Ellipsis: Omitting Repeated Words', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the confusing ellipsis: "The manager approved the first proposal but not the second, which surprised everyone."',
    options: null, correctAnswer: 'The manager approved the first proposal but not the second one, which surprised everyone.',
    explanation: 'Adding "one" after "second" removes ambiguity about exactly what was not approved, since ellipsis should only be used when the omission is completely clear.',
    orderIndex: 107,
  },
  {
    id: 'gq2-108', topic: 'Ellipsis: Omitting Repeated Words', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Complete using ellipsis: "Some workers prefer flexible hours, and some ______ fixed schedules." (omit the repeated verb)',
    options: null, correctAnswer: 'prefer',
    explanation: 'Although ellipsis could omit "prefer" here for conciseness, keeping the parallel verb is also correct — either shows the omitted or repeated word is "prefer".',
    orderIndex: 108,
  },
  {
    id: 'gq2-109', topic: 'Ellipsis: Omitting Repeated Words', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence uses ellipsis appropriately without causing confusion?',
    options: ['She studies economics and her sister law.', 'She studies economics and her sister studies law.', 'She and her sister studies economics and law.', 'Economics she studies and law her sister.'],
    correctAnswer: 'She studies economics and her sister law.',
    explanation: 'The repeated verb "studies" is clearly understood in the second clause from the parallel structure, making the ellipsis unambiguous and natural.',
    orderIndex: 109,
  },
  {
    id: 'gq2-110', topic: 'Ellipsis: Omitting Repeated Words', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error caused by unclear ellipsis: "The company hired more staff and its rival too, but nobody knew who."',
    options: null, correctAnswer: 'The company hired more staff, and its rival hired more staff too, but nobody knew how many.',
    explanation: 'The original ellipsis was too vague to reconstruct clearly; restoring the repeated verb "hired more staff" removes the ambiguity.',
    orderIndex: 110,
  },

  // The Zero Conditional for General Truths
  {
    id: 'gq2-111', topic: 'The Zero Conditional for General Truths', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Which sentence correctly uses the zero conditional?',
    options: ['If you heat water to 100 degrees, it boils.', 'If you heat water to 100 degrees, it will boil.', 'If you heated water to 100 degrees, it boils.', 'If you will heat water to 100 degrees, it boils.'],
    correctAnswer: 'If you heat water to 100 degrees, it boils.',
    explanation: 'The zero conditional uses present simple in both clauses to describe a general truth that is always the case.',
    orderIndex: 111,
  },
  {
    id: 'gq2-112', topic: 'The Zero Conditional for General Truths', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Complete: "If public transport is affordable, more people ______ (use) it instead of driving." (general pattern)',
    options: null, correctAnswer: 'use',
    explanation: 'The zero conditional requires present simple in the main clause as well as the if-clause, so "use" is correct.',
    orderIndex: 112,
  },
  {
    id: 'gq2-113', topic: 'The Zero Conditional for General Truths', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "If prices rise, demand will usually falls."',
    options: null, correctAnswer: 'If prices rise, demand usually falls.',
    explanation: 'A true zero conditional uses present simple in both clauses for a general truth; mixing in "will" incorrectly shifts it toward a first conditional structure.',
    orderIndex: 113,
  },
  {
    id: 'gq2-114', topic: 'The Zero Conditional for General Truths', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence best expresses a general scientific truth using the zero conditional?',
    options: ['Ice melts if the temperature rises above zero.', 'Ice will melt if the temperature rises above zero.', 'Ice melted if the temperature rises above zero.', 'Ice would melt if the temperature rises above zero.'],
    correctAnswer: 'Ice melts if the temperature rises above zero.',
    explanation: 'Present simple in both clauses correctly expresses a general, always-true scientific fact, which is the defining feature of the zero conditional.',
    orderIndex: 114,
  },
  {
    id: 'gq2-115', topic: 'The Zero Conditional for General Truths', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Complete: "______ you heat metal, it expands." (general truth, "when" or "if" both work)',
    options: null, correctAnswer: 'When',
    explanation: '"When" (like "if") can introduce a zero conditional clause describing a general truth, since the outcome is not really in doubt.',
    orderIndex: 115,
  },

  // Causative Verbs: Have and Get Something Done
  {
    id: 'gq2-116', topic: 'Causative Verbs: Have and Get Something Done', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence correctly uses the causative form?',
    options: ['I had my essay checked by a tutor.', 'I had checked my essay by a tutor.', 'I had my essay check by a tutor.', 'I had my essay checking by a tutor.'],
    correctAnswer: 'I had my essay checked by a tutor.',
    explanation: 'The causative structure is "have + object + past participle", so "had my essay checked" is correct.',
    orderIndex: 116,
  },
  {
    id: 'gq2-117', topic: 'Causative Verbs: Have and Get Something Done', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Complete: "We had our house ______ (paint) last year." (someone else did it for us)',
    options: null, correctAnswer: 'painted',
    explanation: 'The causative form requires the past participle "painted" after the object "house", showing someone else performed the action.',
    orderIndex: 117,
  },
  {
    id: 'gq2-118', topic: 'Causative Verbs: Have and Get Something Done', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "She got her hair to cut every month."',
    options: null, correctAnswer: 'She gets her hair cut every month.',
    explanation: 'The causative structure needs the past participle "cut" directly after the object, not a to-infinitive, and the base verb "gets" should match the habitual present tense.',
    orderIndex: 118,
  },
  {
    id: 'gq2-119', topic: 'Causative Verbs: Have and Get Something Done', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence means "I did it myself", not the causative meaning?',
    options: ['I checked my essay.', 'I had my essay checked.', 'I got my essay checked.', 'I had my essay checked by a friend.'],
    correctAnswer: 'I checked my essay.',
    explanation: 'A simple active sentence ("I checked my essay") means the speaker performed the action themselves, unlike the causative forms which mean someone else did it.',
    orderIndex: 119,
  },
  {
    id: 'gq2-120', topic: 'Causative Verbs: Have and Get Something Done', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete: "The company ______ its offices renovated last spring." (causative, past)',
    options: null, correctAnswer: 'had',
    explanation: '"Had" is the causative auxiliary here, followed by the object "its offices" and the past participle "renovated".',
    orderIndex: 120,
  },

  // Question Tags in Spoken English
  {
    id: 'gq2-121', topic: 'Question Tags in Spoken English', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Choose the correct question tag: "The exam was difficult, ______?"',
    options: ["wasn't it", "isn't it", "didn't it", "doesn't it"],
    correctAnswer: "wasn't it",
    explanation: 'The tag must match the auxiliary and tense of the main verb "was", so "wasn\'t it" is correct.',
    orderIndex: 121,
  },
  {
    id: 'gq2-122', topic: 'Question Tags in Spoken English', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Complete: "You have not visited before, ______ you?"',
    options: null, correctAnswer: 'have',
    explanation: 'A negative statement takes a positive tag matching the same auxiliary, so "have you?" is correct after "have not visited".',
    orderIndex: 122,
  },
  {
    id: 'gq2-123', topic: 'Question Tags in Spoken English', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "She has finished the report, doesn\'t she?"',
    options: null, correctAnswer: 'She has finished the report, hasn\'t she?',
    explanation: 'The tag must match the auxiliary of the main verb "has finished", so "hasn\'t she" is correct, not "doesn\'t she".',
    orderIndex: 123,
  },
  {
    id: 'gq2-124', topic: 'Question Tags in Spoken English', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which question tag correctly completes: "They will attend the meeting, ______?"',
    options: ["won't they", "don't they", "isn't it", "wouldn't they"],
    correctAnswer: "won't they",
    explanation: 'The tag must match the modal auxiliary "will" used in the main clause, producing "won\'t they" (will not).',
    orderIndex: 124,
  },
  {
    id: 'gq2-125', topic: 'Question Tags in Spoken English', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Complete: "That is quite a common view, isn\'t ______?"',
    options: null, correctAnswer: 'it',
    explanation: 'The tag pronoun must match the subject of the main clause ("That" refers to "it"), giving "isn\'t it".',
    orderIndex: 125,
  },

  // Common False Friends: Affect/Effect, Its/It's, Then/Than
  {
    id: 'gq2-126', topic: 'Common False Friends: Affect/Effect, Its/It\'s, Then/Than', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Choose the correct sentence.',
    options: ['Rising costs effect low-income families the most.', 'Rising costs affect low-income families the most.', 'Rising costs affects low-income families the most.', 'Rising costs affection low-income families the most.'],
    correctAnswer: 'Rising costs affect low-income families the most.',
    explanation: '"Affect" is the verb meaning to influence something, which is needed here rather than the noun "effect".',
    orderIndex: 126,
  },
  {
    id: 'gq2-127', topic: 'Common False Friends: Affect/Effect, Its/It\'s, Then/Than', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Complete: "The ______ of rising costs is visible in household budgets." (noun meaning result)',
    options: null, correctAnswer: 'effect',
    explanation: '"Effect" is the noun meaning a result, correctly following "the" in this sentence.',
    orderIndex: 127,
  },
  {
    id: 'gq2-128', topic: 'Common False Friends: Affect/Effect, Its/It\'s, Then/Than', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "Prices are higher then they were last year."',
    options: null, correctAnswer: 'Prices are higher than they were last year.',
    explanation: '"Than" is used for comparisons, while "then" refers to time or sequence; this sentence is a comparison, so "than" is correct.',
    orderIndex: 128,
  },
  {
    id: 'gq2-129', topic: 'Common False Friends: Affect/Effect, Its/It\'s, Then/Than', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence correctly distinguishes "its" from "it\'s"?',
    options: ['Its a widely discussed issue.', 'It\'s a widely discussed issue.', 'Its\' a widely discussed issue.', 'It is\'s a widely discussed issue.'],
    correctAnswer: 'It\'s a widely discussed issue.',
    explanation: 'The contraction "it\'s" (meaning "it is") is correct here, since no noun follows to be possessed by "its".',
    orderIndex: 129,
  },
  {
    id: 'gq2-130', topic: 'Common False Friends: Affect/Effect, Its/It\'s, Then/Than', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete: "Prices rose sharply, ______ fell just as quickly." (time/sequence)',
    options: null, correctAnswer: 'then',
    explanation: '"Then" correctly shows a sequence of events in time, unlike "than", which is reserved for comparisons.',
    orderIndex: 130,
  },
];
