import type { GrammarQuestion } from '@/types/models';

/** `topic` matches a GrammarLesson.title exactly, so weak-topic detection
 * (services/repository/learning.ts#weakGrammarTopics) can recommend the
 * right lesson to review. Extends grammarQuestions.ts with ~90 more items
 * covering the same 14 lessons with different example sentences. */
export const grammarQuestions3: GrammarQuestion[] = [
  // Complex Sentences with Subordinate Clauses (7)
  {
    id: 'gq3-1', topic: 'Complex Sentences with Subordinate Clauses', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Choose the best way to combine: "Public transport is cheap. Few commuters use it."',
    options: ['Public transport is cheap, few commuters use it.', 'While public transport is cheap, few commuters use it.', 'Public transport is cheap so few commuters use it well.', 'Cheap is public transport, but commuters do not use it.'],
    correctAnswer: 'While public transport is cheap, few commuters use it.',
    explanation: '"While" introduces a subordinate clause of contrast, correctly combining the two ideas into one complex sentence.',
    orderIndex: 1,
  },
  {
    id: 'gq3-2', topic: 'Complex Sentences with Subordinate Clauses', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Complete the sentence: "The construction project was delayed ______ several key materials were unavailable."',
    options: null, correctAnswer: 'because',
    explanation: '"Because" introduces a subordinate clause giving the reason for the delay, correctly linking cause and effect in one sentence.',
    orderIndex: 2,
  },
  {
    id: 'gq3-3', topic: 'Complex Sentences with Subordinate Clauses', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "Even though the report was thorough, but the committee rejected it."',
    options: null, correctAnswer: 'Even though the report was thorough, the committee rejected it.',
    explanation: 'A clause beginning with "Even though" cannot also be paired with "but" in the main clause — only one contrast word is needed.',
    orderIndex: 3,
  },
  {
    id: 'gq3-4', topic: 'Complex Sentences with Subordinate Clauses', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence correctly uses a subordinate clause of time?',
    options: ['After the factory closed. Hundreds of workers lost their jobs.', 'After the factory closed, hundreds of workers lost their jobs.', 'The factory closed, after hundreds of workers lost their jobs.', 'After, the factory closed hundreds of workers lost their jobs.'],
    correctAnswer: 'After the factory closed, hundreds of workers lost their jobs.',
    explanation: 'The subordinate time clause "After the factory closed" is correctly followed by a comma before the main clause.',
    orderIndex: 4,
  },
  {
    id: 'gq3-5', topic: 'Complex Sentences with Subordinate Clauses', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Complete the sentence: "Many students struggle with time management ______ they first begin university."',
    options: null, correctAnswer: 'when',
    explanation: '"When" introduces a subordinate clause of time, showing at what point the difficulty arises.',
    orderIndex: 5,
  },
  {
    id: 'gq3-6', topic: 'Complex Sentences with Subordinate Clauses', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "Unless the council will approve the budget, the new library cannot be built."',
    options: null, correctAnswer: 'Unless the council approves the budget, the new library cannot be built.',
    explanation: 'After "unless" (a conditional-style subordinator), the verb takes the present simple form, not "will approve" — future meaning is already implied.',
    orderIndex: 6,
  },
  {
    id: 'gq3-7', topic: 'Complex Sentences with Subordinate Clauses', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Choose the sentence that correctly combines these ideas using a subordinate clause: "The team missed the deadline. They had worked overtime for weeks."',
    options: ['The team missed the deadline even though they had worked overtime for weeks.', 'The team missed the deadline, they had worked overtime for weeks.', 'Even though, the team missed the deadline they had worked overtime.', 'The team had worked overtime for weeks, even though missed the deadline.'],
    correctAnswer: 'The team missed the deadline even though they had worked overtime for weeks.',
    explanation: '"Even though" correctly introduces a subordinate clause expressing an unexpected contrast between the effort made and the outcome.',
    orderIndex: 7,
  },

  // Articles: A, An, The, and Zero Article (7)
  {
    id: 'gq3-8', topic: 'Articles: A, An, The, and Zero Article', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Complete: "______ honesty is valued in almost every profession." (general statement about a quality)',
    options: null, correctAnswer: 'no article',
    explanation: 'Uncountable abstract nouns like "honesty" take no article when making a general statement.',
    orderIndex: 8,
  },
  {
    id: 'gq3-9', topic: 'Articles: A, An, The, and Zero Article', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Choose the correct sentence.',
    options: ['The Mount Everest is the tallest mountain in the world.', 'Mount Everest is the tallest mountain in the world.', 'A Mount Everest is tallest mountain in world.', 'The Mount Everest is a tallest mountain in the world.'],
    correctAnswer: 'Mount Everest is the tallest mountain in the world.',
    explanation: 'Most individual mountain names take no article, while "the tallest mountain" correctly uses "the" because superlatives are always specific.',
    orderIndex: 9,
  },
  {
    id: 'gq3-10', topic: 'Articles: A, An, The, and Zero Article', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "The scientists I interviewed earlier study an artificial intelligence."',
    options: null, correctAnswer: 'The scientists I interviewed earlier study artificial intelligence.',
    explanation: '"Artificial intelligence" as a general uncountable field of study takes no article, while "the scientists" correctly uses "the" for a specific, previously mentioned group.',
    orderIndex: 10,
  },
  {
    id: 'gq3-11', topic: 'Articles: A, An, The, and Zero Article', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Complete: "We stayed at ______ hotel near the river that a colleague had recommended."',
    options: null, correctAnswer: 'a',
    explanation: '"A" is used because this is the first mention of the hotel — it is not yet a specific, known item to the listener.',
    orderIndex: 11,
  },
  {
    id: 'gq3-12', topic: 'Articles: A, An, The, and Zero Article', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Choose the correct sentence.',
    options: ['She plays the piano every evening after dinner.', 'She plays piano every evening after dinner.', 'She plays a piano every evening after dinner.', 'She plays an piano every evening after dinner.'],
    correctAnswer: 'She plays the piano every evening after dinner.',
    explanation: 'Musical instruments generally take "the" when referring to playing them as a skill or activity ("play the piano").',
    orderIndex: 12,
  },
  {
    id: 'gq3-13', topic: 'Articles: A, An, The, and Zero Article', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete: "Of all the applicants, she was ______ only one with prior management experience."',
    options: null, correctAnswer: 'the',
    explanation: '"The" is required before "only one," since it specifies a unique item within a defined group (the applicants).',
    orderIndex: 13,
  },
  {
    id: 'gq3-14', topic: 'Articles: A, An, The, and Zero Article', difficulty: 'medium', questionType: 'error_correction',
    prompt: 'Find and correct the error: "The unemployment is rising sharply in the region she described."',
    options: null, correctAnswer: 'Unemployment is rising sharply in the region she described.',
    explanation: '"Unemployment" is an uncountable noun referring to a general concept here, so it should take no article, unlike "the region," which correctly refers to a specific, previously mentioned place.',
    orderIndex: 14,
  },

  // Conditionals for Hypothetical Situations (7)
  {
    id: 'gq3-15', topic: 'Conditionals for Hypothetical Situations', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence correctly uses the third conditional?',
    options: ['If the company had listened to feedback, it would not have lost customers.', 'If the company listened to feedback, it would not lose customers.', 'If the company would have listened to feedback, it will not lose customers.', 'If the company has listened to feedback, it would not have lost customers.'],
    correctAnswer: 'If the company had listened to feedback, it would not have lost customers.',
    explanation: 'The third conditional needs "had + past participle" in the if-clause and "would have + past participle" in the main clause to describe a hypothetical past.',
    orderIndex: 15,
  },
  {
    id: 'gq3-16', topic: 'Conditionals for Hypothetical Situations', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete the second conditional: "If I ______ (be) the mayor, I would ban cars from the city centre."',
    options: null, correctAnswer: 'were',
    explanation: 'In formal second conditional usage, "were" is used for all subjects (including "I") rather than "was," describing a hypothetical present situation.',
    orderIndex: 16,
  },
  {
    id: 'gq3-17', topic: 'Conditionals for Hypothetical Situations', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Choose the correct first conditional sentence.',
    options: ['If the weather improves, more tourists will visit the island.', 'If the weather will improve, more tourists visit the island.', 'If the weather improves, more tourists would visit the island.', 'If the weather improved, more tourists will visit the island.'],
    correctAnswer: 'If the weather improves, more tourists will visit the island.',
    explanation: 'The first conditional pairs present simple in the if-clause with "will" in the main clause to describe a realistic future outcome.',
    orderIndex: 17,
  },
  {
    id: 'gq3-18', topic: 'Conditionals for Hypothetical Situations', difficulty: 'medium', questionType: 'error_correction',
    prompt: 'Find and correct the error: "If the museum was renovated last year, it would attract more visitors now."',
    options: null, correctAnswer: 'If the museum had been renovated last year, it would attract more visitors now.',
    explanation: 'This is a mixed conditional describing a past hypothetical cause with a present hypothetical result, so the if-clause needs "had been renovated," not the simple past.',
    orderIndex: 18,
  },
  {
    id: 'gq3-19', topic: 'Conditionals for Hypothetical Situations', difficulty: 'hard', questionType: 'multiple_choice',
    prompt: 'Choose the sentence that correctly expresses a zero conditional (general truth).',
    options: ['If you heat metal, it expands.', 'If you heat metal, it will expand.', 'If you heated metal, it expands.', 'If you heat metal, it would expand.'],
    correctAnswer: 'If you heat metal, it expands.',
    explanation: 'The zero conditional uses present simple in both clauses to describe a general scientific fact that is always true.',
    orderIndex: 19,
  },
  {
    id: 'gq3-20', topic: 'Conditionals for Hypothetical Situations', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Complete: "Fewer accidents ______ (occur) if speed limits were enforced more strictly."',
    options: null, correctAnswer: 'would occur',
    explanation: 'In a second conditional, the main clause takes "would + base verb," giving "would occur" to match the hypothetical if-clause "were enforced."',
    orderIndex: 20,
  },
  {
    id: 'gq3-21', topic: 'Conditionals for Hypothetical Situations', difficulty: 'easy', questionType: 'error_correction',
    prompt: 'Find and correct the error: "If she study harder, she will pass the exam."',
    options: null, correctAnswer: 'If she studies harder, she will pass the exam.',
    explanation: 'The if-clause of a first conditional needs the present simple form of the verb with third-person "she," so "studies," not "study."',
    orderIndex: 21,
  },

  // Linking Devices for Coherence (7)
  {
    id: 'gq3-22', topic: 'Linking Devices for Coherence', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Which linking word best completes: "The new policy reduced traffic congestion. ______, air quality in the city centre improved."',
    options: ['However', 'Consequently', 'For instance', 'Whereas'],
    correctAnswer: 'Consequently',
    explanation: '"Consequently" signals a result — improved air quality followed as a consequence of reduced congestion.',
    orderIndex: 22,
  },
  {
    id: 'gq3-23', topic: 'Linking Devices for Coherence', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Complete: "Online learning offers flexibility. ______, it requires strong self-discipline."',
    options: null, correctAnswer: 'However',
    explanation: '"However" correctly signals the contrast between the benefit of flexibility and the drawback of requiring self-discipline.',
    orderIndex: 23,
  },
  {
    id: 'gq3-24', topic: 'Linking Devices for Coherence', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "Despite the price increased, sales remained strong."',
    options: null, correctAnswer: 'Despite the price increase, sales remained strong. (or: Despite the fact that the price increased, sales remained strong.)',
    explanation: '"Despite" must be followed by a noun phrase, not a full clause with a finite verb — "the price increased" needs to become a noun phrase or be introduced with "the fact that."',
    orderIndex: 24,
  },
  {
    id: 'gq3-25', topic: 'Linking Devices for Coherence', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which linking word best completes: "Some students prefer group projects; ______, others work better independently."',
    options: ['moreover', 'in contrast', 'therefore', 'similarly'],
    correctAnswer: 'in contrast',
    explanation: '"In contrast" correctly signals the opposing preference described in the second half of the sentence.',
    orderIndex: 25,
  },
  {
    id: 'gq3-26', topic: 'Linking Devices for Coherence', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Complete: "The bridge is structurally sound; ______, engineers recommend regular inspections."',
    options: null, correctAnswer: 'nevertheless',
    explanation: '"Nevertheless" signals that inspections are still recommended despite the bridge being sound, showing contrast between the two facts.',
    orderIndex: 26,
  },
  {
    id: 'gq3-27', topic: 'Linking Devices for Coherence', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "The plan reduced costs. Also, it it made the process slower."',
    options: null, correctAnswer: 'The plan reduced costs. However, it made the process slower.',
    explanation: '"Also" wrongly signals addition when the second idea (slower process) actually contrasts with the first (reduced costs); "However" is needed instead, and the repeated "it it" is a typo to remove.',
    orderIndex: 27,
  },
  {
    id: 'gq3-28', topic: 'Linking Devices for Coherence', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Choose the best linking phrase: "Many companies now allow remote work. ______, employees report higher job satisfaction."',
    options: ['As a result', 'Despite this', 'On the contrary', 'Nonetheless'],
    correctAnswer: 'As a result',
    explanation: '"As a result" correctly signals that higher job satisfaction is a consequence of companies allowing remote work.',
    orderIndex: 28,
  },

  // Subject-Verb Agreement (6)
  {
    id: 'gq3-29', topic: 'Subject-Verb Agreement', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Choose the correct sentence.',
    options: ['Each of the students have submitted their assignment.', 'Each of the students has submitted their assignment.', 'Each of the students submit their assignment.', 'Each of the students are submitting their assignment.'],
    correctAnswer: 'Each of the students has submitted their assignment.',
    explanation: '"Each" is grammatically singular, so it takes a singular verb ("has"), even though it refers to multiple students.',
    orderIndex: 29,
  },
  {
    id: 'gq3-30', topic: 'Subject-Verb Agreement', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete: "The committee ______ (be) divided on how to allocate the budget." (members disagreeing individually)',
    options: null, correctAnswer: 'are',
    explanation: 'When a collective noun like "committee" is described as acting or thinking as separate individuals rather than as one unit, it takes a plural verb.',
    orderIndex: 30,
  },
  {
    id: 'gq3-31', topic: 'Subject-Verb Agreement', difficulty: 'easy', questionType: 'error_correction',
    prompt: 'Find and correct the error: "The list of requirements are attached to the email."',
    options: null, correctAnswer: 'The list of requirements is attached to the email.',
    explanation: 'The true subject is "the list" (singular), not the nearby plural noun "requirements," so the verb must be "is."',
    orderIndex: 31,
  },
  {
    id: 'gq3-32', topic: 'Subject-Verb Agreement', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Choose the correct sentence.',
    options: ['Neither the manager nor the staff was informed of the change.', 'Neither the manager nor the staff were informed of the change.', 'Neither the manager or the staff was informed of the change.', 'Neither the manager nor the staff informed of the change.'],
    correctAnswer: 'Neither the manager nor the staff were informed of the change.',
    explanation: 'With "neither...nor," the verb agrees with the noun closest to it — since "staff" is treated as plural here, the verb is "were."',
    orderIndex: 32,
  },
  {
    id: 'gq3-33', topic: 'Subject-Verb Agreement', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete: "Economics ______ (be) considered a difficult subject by many first-year students."',
    options: null, correctAnswer: 'is',
    explanation: '"Economics" is a subject name ending in -s that is treated as a singular uncountable noun, so it takes the singular verb "is."',
    orderIndex: 33,
  },
  {
    id: 'gq3-34', topic: 'Subject-Verb Agreement', difficulty: 'medium', questionType: 'error_correction',
    prompt: 'Find and correct the error: "The benefits of regular exercise, which many doctors recommend, remains underestimated."',
    options: null, correctAnswer: 'The benefits of regular exercise, which many doctors recommend, remain underestimated.',
    explanation: 'The true subject is the plural noun "benefits," so the verb must agree with it as "remain," despite the intervening singular clause.',
    orderIndex: 34,
  },
  {
    id: 'gq3-89', topic: 'Subject-Verb Agreement', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Choose the correct sentence.',
    options: ['Ten kilometres are a long distance to walk in one day.', 'Ten kilometres is a long distance to walk in one day.', 'Ten kilometres were a long distance to walk in one day.', 'Ten kilometres has a long distance to walk in one day.'],
    correctAnswer: 'Ten kilometres is a long distance to walk in one day.',
    explanation: 'A distance, amount, or period of time expressed as a single unit is treated as singular, so it takes the singular verb "is."',
    orderIndex: 89,
  },

  // Prepositions Commonly Confused in IELTS Writing (7)
  {
    id: 'gq3-35', topic: 'Prepositions Commonly Confused in IELTS Writing', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Complete: "This approach differs significantly ______ the traditional method."',
    options: null, correctAnswer: 'from',
    explanation: '"Differ from" is the standard preposition combination in formal academic writing, unlike "differ than," which is nonstandard.',
    orderIndex: 35,
  },
  {
    id: 'gq3-36', topic: 'Prepositions Commonly Confused in IELTS Writing', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Choose the correct sentence.',
    options: ['The findings are consistent to previous research.', 'The findings are consistent with previous research.', 'The findings are consistent of previous research.', 'The findings are consistent in previous research.'],
    correctAnswer: 'The findings are consistent with previous research.',
    explanation: '"Consistent with" is the correct fixed preposition combination in academic writing.',
    orderIndex: 36,
  },
  {
    id: 'gq3-37', topic: 'Prepositions Commonly Confused in IELTS Writing', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete: "The company was criticised ______ its handling of customer complaints."',
    options: null, correctAnswer: 'for',
    explanation: '"Criticised for [reason]" is the standard collocation, unlike "criticised of," which is incorrect.',
    orderIndex: 37,
  },
  {
    id: 'gq3-38', topic: 'Prepositions Commonly Confused in IELTS Writing', difficulty: 'medium', questionType: 'error_correction',
    prompt: 'Find and correct the error: "The number of students applying to the course has decreased of 15 percent."',
    options: null, correctAnswer: 'The number of students applying to the course has decreased by 15 percent.',
    explanation: '"Decreased by [amount]" is the correct preposition for stating a specific quantity of change, not "decreased of."',
    orderIndex: 38,
  },
  {
    id: 'gq3-39', topic: 'Prepositions Commonly Confused in IELTS Writing', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Choose the correct sentence.',
    options: ['She is married with a doctor.', 'She is married to a doctor.', 'She is married for a doctor.', 'She is married on a doctor.'],
    correctAnswer: 'She is married to a doctor.',
    explanation: '"Married to" is the correct fixed preposition combination in English.',
    orderIndex: 39,
  },
  {
    id: 'gq3-40', topic: 'Prepositions Commonly Confused in IELTS Writing', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete: "Access ______ clean water remains limited in several rural regions."',
    options: null, correctAnswer: 'to',
    explanation: '"Access to [something]" is the standard collocation, unlike "access of," which is incorrect.',
    orderIndex: 40,
  },
  {
    id: 'gq3-90', topic: 'Prepositions Commonly Confused in IELTS Writing', difficulty: 'medium', questionType: 'error_correction',
    prompt: 'Find and correct the error: "The findings of this study are similar with those reported in earlier surveys."',
    options: null, correctAnswer: 'The findings of this study are similar to those reported in earlier surveys.',
    explanation: '"Similar to" is the correct fixed preposition combination, not "similar with."',
    orderIndex: 90,
  },

  // The Passive Voice for Formal and Academic Register (6)
  {
    id: 'gq3-41', topic: 'The Passive Voice for Formal and Academic Register', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Which sentence best uses the passive voice for a Task 1 diagram step?',
    options: ['Workers sort the recyclable materials by hand.', 'The recyclable materials are sorted by hand.', 'The recyclable materials sort by hand.', 'Sorting the recyclable materials is by hand workers.'],
    correctAnswer: 'The recyclable materials are sorted by hand.',
    explanation: 'The passive form ("are sorted") appropriately shifts focus onto the process step rather than the unnamed workers performing it.',
    orderIndex: 41,
  },
  {
    id: 'gq3-42', topic: 'The Passive Voice for Formal and Academic Register', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Rewrite in the passive: "The government will announce new regulations next month." → "New regulations ______ next month."',
    options: null, correctAnswer: 'will be announced',
    explanation: 'In the future simple passive, the auxiliary structure is "will be + past participle," giving "will be announced."',
    orderIndex: 42,
  },
  {
    id: 'gq3-43', topic: 'The Passive Voice for Formal and Academic Register', difficulty: 'medium', questionType: 'error_correction',
    prompt: 'Find and correct the error: "The survey results have been analyse by a team of statisticians."',
    options: null, correctAnswer: 'The survey results have been analysed by a team of statisticians.',
    explanation: 'The present perfect passive requires the past participle "analysed," not the base form "analyse," after "have been."',
    orderIndex: 43,
  },
  {
    id: 'gq3-44', topic: 'The Passive Voice for Formal and Academic Register', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Choose the sentence that sounds more formal and objective for an academic essay.',
    options: ['I think that the policy needs urgent reform.', 'It is widely believed that the policy needs urgent reform.', 'People think the policy needs urgent reform.', 'You should think the policy needs urgent reform.'],
    correctAnswer: 'It is widely believed that the policy needs urgent reform.',
    explanation: 'The passive construction "It is widely believed that..." removes the personal "I think" and sounds more formal and objective, suited to academic register.',
    orderIndex: 44,
  },
  {
    id: 'gq3-45', topic: 'The Passive Voice for Formal and Academic Register', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Rewrite in the passive: "Engineers are currently testing the new engine design." → "The new engine design ______ currently ______ by engineers."',
    options: null, correctAnswer: 'is / being tested',
    explanation: 'The present continuous passive is formed with "is/are being + past participle," giving "is currently being tested."',
    orderIndex: 45,
  },
  {
    id: 'gq3-46', topic: 'The Passive Voice for Formal and Academic Register', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Choose the correctly formed passive sentence.',
    options: ['The proposal was rejecting by the board last week.', 'The proposal was rejected by the board last week.', 'The proposal rejected by the board last week.', 'The proposal is rejected by the board last week.'],
    correctAnswer: 'The proposal was rejected by the board last week.',
    explanation: 'The past simple passive correctly pairs "was" with the past participle "rejected" to match the past time marker "last week."',
    orderIndex: 46,
  },

  // Relative Clauses: Defining and Non-Defining (6)
  {
    id: 'gq3-47', topic: 'Relative Clauses: Defining and Non-Defining', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Choose the correctly punctuated sentence.',
    options: ['The report, that was published last year, revealed serious flaws.', 'The report, which was published last year, revealed serious flaws.', 'The report which was published last year revealed, serious flaws.', 'The report that, was published last year, revealed serious flaws.'],
    correctAnswer: 'The report, which was published last year, revealed serious flaws.',
    explanation: 'This is a non-defining relative clause adding extra information about a specific, already-identified report, so it must use commas and "which," never "that."',
    orderIndex: 47,
  },
  {
    id: 'gq3-48', topic: 'Relative Clauses: Defining and Non-Defining', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Complete: "The book ______ I borrowed from the library was fascinating." (defining clause, object of the verb)',
    options: null, correctAnswer: 'that',
    explanation: '"That" (or "which") is used to introduce a defining relative clause identifying which specific book is meant, with no comma needed.',
    orderIndex: 48,
  },
  {
    id: 'gq3-49', topic: 'Relative Clauses: Defining and Non-Defining', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "Employees which arrive late three times will receive a formal warning."',
    options: null, correctAnswer: 'Employees who arrive late three times will receive a formal warning.',
    explanation: '"Which" is used for things, not people — a defining relative clause about people needs "who" (or "that").',
    orderIndex: 49,
  },
  {
    id: 'gq3-50', topic: 'Relative Clauses: Defining and Non-Defining', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Choose the correctly punctuated sentence.',
    options: ['Dr. Lin who leads the research team has published widely on climate policy.', 'Dr. Lin, who leads the research team, has published widely on climate policy.', 'Dr. Lin, that leads the research team, has published widely on climate policy.', 'Dr. Lin who, leads the research team has published widely on climate policy.'],
    correctAnswer: 'Dr. Lin, who leads the research team, has published widely on climate policy.',
    explanation: 'Since "Dr. Lin" is already a specific, named individual, the clause is non-defining extra information and must be set off with commas and "who," not "that."',
    orderIndex: 50,
  },
  {
    id: 'gq3-51', topic: 'Relative Clauses: Defining and Non-Defining', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete: "The factory, ______ was built in the 1960s, is scheduled for demolition next year." (non-defining, refers to a thing)',
    options: null, correctAnswer: 'which',
    explanation: 'Since the clause is set off by commas and adds extra, non-essential information about a thing, "which" is required rather than "that."',
    orderIndex: 51,
  },
  {
    id: 'gq3-52', topic: 'Relative Clauses: Defining and Non-Defining', difficulty: 'medium', questionType: 'error_correction',
    prompt: 'Find and correct the error: "The applicants, who submitted their forms after the deadline, were still considered."',
    options: null, correctAnswer: 'The applicants who submitted their forms after the deadline were still considered.',
    explanation: 'The clause identifies exactly which applicants are meant (only those who submitted late), so it is defining and should not be separated by commas.',
    orderIndex: 52,
  },

  // Reported Speech in Speaking and Writing (6)
  {
    id: 'gq3-53', topic: 'Reported Speech in Speaking and Writing', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Report this statement: Direct: "I have finished the project." → Reported: He said he ______ the project.',
    options: null, correctAnswer: 'had finished',
    explanation: 'Present perfect ("have finished") backshifts to past perfect ("had finished") in reported speech.',
    orderIndex: 53,
  },
  {
    id: 'gq3-54', topic: 'Reported Speech in Speaking and Writing', difficulty: 'hard', questionType: 'multiple_choice',
    prompt: 'Choose the correct reported version of: "I can meet you here next week."',
    options: ['She said she can meet me here next week.', 'She said she could meet me there the following week.', 'She said she could meet me here next week.', 'She said she can meet me there the following week.'],
    correctAnswer: 'She said she could meet me there the following week.',
    explanation: '"Can" backshifts to "could," and the place/time words "here" and "next week" change to "there" and "the following week" in reported speech.',
    orderIndex: 54,
  },
  {
    id: 'gq3-55', topic: 'Reported Speech in Speaking and Writing', difficulty: 'medium', questionType: 'error_correction',
    prompt: 'Find and correct the error: "He told that he would call me back later."',
    options: null, correctAnswer: 'He said that he would call me back later. (or: He told me that he would call me back later.)',
    explanation: '"Told" must be followed by a personal object ("told me"), whereas "said" does not require one — one of the two fixes is needed.',
    orderIndex: 55,
  },
  {
    id: 'gq3-56', topic: 'Reported Speech in Speaking and Writing', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Report this question: Direct: "Where do you live?" → Reported: She asked me where I ______.',
    options: null, correctAnswer: 'lived',
    explanation: 'Reported questions backshift the tense and use normal statement word order, so "do you live" becomes "I lived."',
    orderIndex: 56,
  },
  {
    id: 'gq3-57', topic: 'Reported Speech in Speaking and Writing', difficulty: 'hard', questionType: 'multiple_choice',
    prompt: 'Choose the sentence using the most precise reporting verb for someone reluctantly confessing a mistake.',
    options: ['He suggested that he had made a mistake.', 'He admitted that he had made a mistake.', 'He argued that he had made a mistake.', 'He claimed that he had made a mistake.'],
    correctAnswer: 'He admitted that he had made a mistake.',
    explanation: '"Admitted" specifically conveys reluctant acknowledgment of a mistake, which is more precise than the neutral "suggested" or "claimed."',
    orderIndex: 57,
  },
  {
    id: 'gq3-58', topic: 'Reported Speech in Speaking and Writing', difficulty: 'medium', questionType: 'error_correction',
    prompt: 'Find and correct the error: "The manager said that the meeting will start at 9am tomorrow."',
    options: null, correctAnswer: 'The manager said that the meeting would start at 9am the next day.',
    explanation: 'In reported speech, "will" backshifts to "would," and "tomorrow" changes to "the next day" relative to the original statement.',
    orderIndex: 58,
  },

  // Modal Verbs for Degrees of Certainty and Obligation (6)
  {
    id: 'gq3-59', topic: 'Modal Verbs for Degrees of Certainty and Obligation', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Which modal best expresses a possibility that is not certain?',
    options: ['must', 'might', 'have to', 'should'],
    correctAnswer: 'might',
    explanation: '"Might" expresses a tentative possibility, unlike "must," which expresses near-certainty based on strong evidence.',
    orderIndex: 59,
  },
  {
    id: 'gq3-60', topic: 'Modal Verbs for Degrees of Certainty and Obligation', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Complete (expressing a strict legal requirement): "All employees ______ complete the safety training before starting work."',
    options: null, correctAnswer: 'must',
    explanation: '"Must" expresses a mandatory requirement, appropriate for a strict rule such as a legal safety requirement.',
    orderIndex: 60,
  },
  {
    id: 'gq3-61', topic: 'Modal Verbs for Degrees of Certainty and Obligation', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "Given how quiet the office is, everyone must have leave early today."',
    options: null, correctAnswer: 'Given how quiet the office is, everyone must have left early today.',
    explanation: 'A modal of past deduction needs "must have + past participle," so "left," not the base form "leave," is required.',
    orderIndex: 61,
  },
  {
    id: 'gq3-62', topic: 'Modal Verbs for Degrees of Certainty and Obligation', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Choose the sentence that correctly expresses absence of obligation.',
    options: ['Visitors mustn\'t sign in at the front desk.', 'Visitors don\'t have to sign in at the front desk.', 'Visitors shouldn\'t sign in at the front desk.', 'Visitors can\'t sign in at the front desk.'],
    correctAnswer: 'Visitors don\'t have to sign in at the front desk.',
    explanation: '"Don\'t have to" expresses that an action is optional (no obligation), whereas "mustn\'t" would incorrectly express prohibition.',
    orderIndex: 62,
  },
  {
    id: 'gq3-63', topic: 'Modal Verbs for Degrees of Certainty and Obligation', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete (expressing weak possibility about a past event): "The delay ______ have been caused by a technical fault, though no one is certain."',
    options: null, correctAnswer: 'could',
    explanation: '"Could have been" expresses a tentative, uncertain possibility about a past event, matching the phrase "no one is certain."',
    orderIndex: 63,
  },
  {
    id: 'gq3-64', topic: 'Modal Verbs for Degrees of Certainty and Obligation', difficulty: 'easy', questionType: 'error_correction',
    prompt: 'Find and correct the error: "Students should to submit their essays by Friday."',
    options: null, correctAnswer: 'Students should submit their essays by Friday.',
    explanation: 'Modal verbs like "should" are followed directly by the base form of the verb, without "to."',
    orderIndex: 64,
  },

  // Comparatives and Superlatives for Task 1 Comparisons (6)
  {
    id: 'gq3-65', topic: 'Comparatives and Superlatives for Task 1 Comparisons', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Complete: "Of the three regions shown, the north had the ______ (low) rainfall in 2019."',
    options: null, correctAnswer: 'lowest',
    explanation: 'Comparing three or more items requires the superlative form, and "low" is a short adjective that takes "-est."',
    orderIndex: 65,
  },
  {
    id: 'gq3-66', topic: 'Comparatives and Superlatives for Task 1 Comparisons', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Choose the correct comparative form of "reliable."',
    options: ['reliabler', 'more reliable', 'most reliable', 'reliablest'],
    correctAnswer: 'more reliable',
    explanation: 'Adjectives of three or more syllables like "reliable" form the comparative with "more," not with an "-er" ending.',
    orderIndex: 66,
  },
  {
    id: 'gq3-67', topic: 'Comparatives and Superlatives for Task 1 Comparisons', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "Sales in the third quarter were nearly two times more than in the first quarter."',
    options: null, correctAnswer: 'Sales in the third quarter were nearly twice as much as in the first quarter.',
    explanation: '"Two times more than" is an awkward, imprecise construction in formal Task 1 writing; the standard comparative phrase for this relationship is "twice as much as."',
    orderIndex: 67,
  },
  {
    id: 'gq3-68', topic: 'Comparatives and Superlatives for Task 1 Comparisons', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Complete: "Female graduates outnumbered male graduates, though the gap was ______ (marginal) than in previous years."',
    options: null, correctAnswer: 'more marginal',
    explanation: '"Marginal" is a two-syllable adjective that does not follow the simple -er pattern comfortably, so the comparative is formed with "more."',
    orderIndex: 68,
  },
  {
    id: 'gq3-69', topic: 'Comparatives and Superlatives for Task 1 Comparisons', difficulty: 'hard', questionType: 'multiple_choice',
    prompt: 'Which sentence uses the irregular comparative correctly?',
    options: ['Public transport usage was gooder in the capital than in rural areas.', 'Public transport usage was better in the capital than in rural areas.', 'Public transport usage was more good in the capital than in rural areas.', 'Public transport usage was bestly in the capital than in rural areas.'],
    correctAnswer: 'Public transport usage was better in the capital than in rural areas.',
    explanation: '"Good" has the irregular comparative form "better," not "gooder" or "more good."',
    orderIndex: 69,
  },
  {
    id: 'gq3-70', topic: 'Comparatives and Superlatives for Task 1 Comparisons', difficulty: 'easy', questionType: 'error_correction',
    prompt: 'Find and correct the error: "This was the most easiest year to compare, since the data followed a clear trend."',
    options: null, correctAnswer: 'This was the easiest year to compare, since the data followed a clear trend.',
    explanation: '"Easiest" already is the superlative form of the short adjective "easy," so adding "most" creates a double superlative error.',
    orderIndex: 70,
  },

  // Parallel Structure in Lists and Comparisons (6)
  {
    id: 'gq3-71', topic: 'Parallel Structure in Lists and Comparisons', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Choose the sentence with correct parallel structure.',
    options: ['The course teaches students to write clearly, to think critically, and analyzing data.', 'The course teaches students to write clearly, to think critically, and to analyze data.', 'The course teaches students writing clearly, to think critically, and to analyze data.', 'The course teaches students to write clearly, thinking critically, and to analyze data.'],
    correctAnswer: 'The course teaches students to write clearly, to think critically, and to analyze data.',
    explanation: 'All three items use the same "to + base verb" pattern ("to write," "to think," "to analyze"), keeping the list parallel.',
    orderIndex: 71,
  },
  {
    id: 'gq3-72', topic: 'Parallel Structure in Lists and Comparisons', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "The new manager is efficient, reliable, and shows creativity."',
    options: null, correctAnswer: 'The new manager is efficient, reliable, and creative.',
    explanation: 'The list should consist of matching adjectives ("efficient, reliable, creative"), not switch to a verb phrase ("shows creativity") for the final item.',
    orderIndex: 72,
  },
  {
    id: 'gq3-73', topic: 'Parallel Structure in Lists and Comparisons', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Complete to keep the list parallel: "The survey aims to identify customer needs, measure satisfaction levels, and ______ (improve) service quality."',
    options: null, correctAnswer: 'improve',
    explanation: 'Matching the base-verb pattern of "identify" and "measure," the third item should also use the base form "improve."',
    orderIndex: 73,
  },
  {
    id: 'gq3-74', topic: 'Parallel Structure in Lists and Comparisons', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "Working from home is just as productive as to work in an office, according to the study."',
    options: null, correctAnswer: 'Working from home is just as productive as working in an office, according to the study.',
    explanation: 'Both sides of an "as...as" comparison must use the same grammatical form — "working" (-ing) must match "working," not switch to "to work."',
    orderIndex: 74,
  },
  {
    id: 'gq3-75', topic: 'Parallel Structure in Lists and Comparisons', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Choose the sentence with correct parallel structure.',
    options: ['She enjoys hiking, swimming, and to cycle on weekends.', 'She enjoys hiking, swimming, and cycling on weekends.', 'She enjoys to hike, swimming, and cycling on weekends.', 'She enjoys hiking, to swim, and cycling on weekends.'],
    correctAnswer: 'She enjoys hiking, swimming, and cycling on weekends.',
    explanation: 'All three activities use the matching -ing form ("hiking," "swimming," "cycling"), keeping the list grammatically parallel.',
    orderIndex: 75,
  },
  {
    id: 'gq3-76', topic: 'Parallel Structure in Lists and Comparisons', difficulty: 'medium', questionType: 'fill_blank',
    prompt: 'Complete to keep the comparison parallel: "Renting an apartment can be as expensive as ______ (own) one, once maintenance costs are included."',
    options: null, correctAnswer: 'owning',
    explanation: 'Since the first half of the comparison uses "renting" (-ing form), the second half must also use the -ing form, "owning," to remain parallel.',
    orderIndex: 76,
  },

  // Punctuation: Commas, Semicolons, and Run-on Sentences (6)
  {
    id: 'gq3-77', topic: 'Punctuation: Commas, Semicolons, and Run-on Sentences', difficulty: 'medium', questionType: 'error_correction',
    prompt: 'Find and correct the comma splice: "The data was incomplete, the researchers still published their findings."',
    options: null, correctAnswer: 'The data was incomplete; the researchers still published their findings. (or: The data was incomplete, but the researchers still published their findings.)',
    explanation: 'Two complete sentences cannot be joined by a comma alone — a semicolon or a coordinating conjunction such as "but" is required.',
    orderIndex: 77,
  },
  {
    id: 'gq3-78', topic: 'Punctuation: Commas, Semicolons, and Run-on Sentences', difficulty: 'easy', questionType: 'multiple_choice',
    prompt: 'Which sentence is correctly punctuated?',
    options: ['Although the budget was tight the project finished on time.', 'Although the budget was tight, the project finished on time.', 'Although, the budget was tight the project finished on time.', 'Although the budget was tight; the project finished on time.'],
    correctAnswer: 'Although the budget was tight, the project finished on time.',
    explanation: 'A comma is required after an introductory subordinate clause ("Although the budget was tight") before the main clause begins.',
    orderIndex: 78,
  },
  {
    id: 'gq3-79', topic: 'Punctuation: Commas, Semicolons, and Run-on Sentences', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete with the correct punctuation mark: "The proposal was well researched___ however, it lacked a realistic budget."',
    options: null, correctAnswer: ';',
    explanation: 'A semicolon is needed before a linking adverb like "however" when it joins two complete sentences, followed by a comma after "however."',
    orderIndex: 79,
  },
  {
    id: 'gq3-80', topic: 'Punctuation: Commas, Semicolons, and Run-on Sentences', difficulty: 'medium', questionType: 'error_correction',
    prompt: 'Find and correct the run-on sentence: "The lecture ran long students started leaving before it ended."',
    options: null, correctAnswer: 'The lecture ran long, so students started leaving before it ended. (or: The lecture ran long; students started leaving before it ended.)',
    explanation: 'Two complete sentences cannot simply be placed next to each other with no punctuation — a conjunction, semicolon, or full stop is required to separate them.',
    orderIndex: 80,
  },
  {
    id: 'gq3-81', topic: 'Punctuation: Commas, Semicolons, and Run-on Sentences', difficulty: 'hard', questionType: 'multiple_choice',
    prompt: 'Which sentence correctly uses a semicolon?',
    options: ['The results were promising; therefore, the team requested more funding.', 'The results were promising, therefore; the team requested more funding.', 'The results were promising therefore; the team requested more funding.', 'The results were promising; therefore the team, requested more funding.'],
    correctAnswer: 'The results were promising; therefore, the team requested more funding.',
    explanation: 'The semicolon correctly joins two complete sentences, and the linking adverb "therefore" that follows it takes its own comma.',
    orderIndex: 81,
  },
  {
    id: 'gq3-82', topic: 'Punctuation: Commas, Semicolons, and Run-on Sentences', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Complete: "In addition___ the report recommends hiring two more analysts." (comma after introductory linking phrase)',
    options: null, correctAnswer: ',',
    explanation: 'A comma is required after the introductory linking phrase "In addition" before the main clause begins.',
    orderIndex: 82,
  },

  // Word Order in Indirect and Embedded Questions (6)
  {
    id: 'gq3-83', topic: 'Word Order in Indirect and Embedded Questions', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "Researchers are still investigating why does this species migrate so far."',
    options: null, correctAnswer: 'Researchers are still investigating why this species migrates so far.',
    explanation: 'Once embedded after "investigating," the clause returns to statement word order and drops the auxiliary "does," which was only needed in the original direct question.',
    orderIndex: 83,
  },
  {
    id: 'gq3-84', topic: 'Word Order in Indirect and Embedded Questions', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Choose the correctly embedded question.',
    options: ['Nobody knows how much does the project cost.', 'Nobody knows how much the project costs.', 'Nobody knows how much costs the project.', 'Nobody knows how much the project does cost.'],
    correctAnswer: 'Nobody knows how much the project costs.',
    explanation: 'Embedded questions use normal statement word order (subject before verb) and drop the auxiliary "does."',
    orderIndex: 84,
  },
  {
    id: 'gq3-85', topic: 'Word Order in Indirect and Embedded Questions', difficulty: 'easy', questionType: 'fill_blank',
    prompt: 'Complete: "Could you tell me where the nearest train station ______ (be)?" (embedded question, polite request)',
    options: null, correctAnswer: 'is',
    explanation: 'The embedded question after "tell me" uses normal statement word order, so "is" follows the subject rather than coming before it.',
    orderIndex: 85,
  },
  {
    id: 'gq3-86', topic: 'Word Order in Indirect and Embedded Questions', difficulty: 'hard', questionType: 'error_correction',
    prompt: 'Find and correct the error: "It remains unclear how many people did attend the protest."',
    options: null, correctAnswer: 'It remains unclear how many people attended the protest.',
    explanation: 'In an embedded question, the auxiliary "did" is dropped and the main verb takes the past tense form directly ("attended"), following normal statement word order.',
    orderIndex: 86,
  },
  {
    id: 'gq3-87', topic: 'Word Order in Indirect and Embedded Questions', difficulty: 'medium', questionType: 'multiple_choice',
    prompt: 'Choose the correctly embedded question.',
    options: ['I am not certain what time does the meeting start.', 'I am not certain what time the meeting starts.', 'I am not certain what time starts the meeting.', 'I am not certain what time the meeting does start.'],
    correctAnswer: 'I am not certain what time the meeting starts.',
    explanation: 'Embedded questions follow statement word order, placing the subject "the meeting" before the verb "starts" and dropping "does."',
    orderIndex: 87,
  },
  {
    id: 'gq3-88', topic: 'Word Order in Indirect and Embedded Questions', difficulty: 'hard', questionType: 'fill_blank',
    prompt: 'Complete: "Survey respondents were asked how often they ______ (use) public transport." (embedded question, past tense)',
    options: null, correctAnswer: 'used',
    explanation: 'The embedded question uses normal statement word order and the simple past form "used," rather than "did use" or question word order.',
    orderIndex: 88,
  },
];
