-- Superseded by 0002_generated_content.sql (auto-generated via `npm run seed:generate` from lib/content/*.ts). Intentionally left empty so it is still applied harmlessly if a stale checkout runs it.
