// Regenerates supabase/seed/0002_generated_content.sql from lib/content/*.ts.
//
// lib/content/*.ts is the single source of truth for all bundled IELTS
// content (lessons, reading, listening, writing, speaking, vocabulary,
// grammar, achievements, mock tests). This script derives the matching
// Supabase seed SQL automatically so the two never drift as the content
// library grows to dozens of passages, tracks, and mock tests — nobody
// hand-writes SQL for new content going forward.
//
// Usage: npm run seed:generate

import fs from 'node:fs';
import path from 'node:path';

import { content } from '../lib/content';

const OUT_PATH = path.join(__dirname, '..', 'supabase', 'seed', '0002_generated_content.sql');

function sqlStr(value: string | null | undefined): string {
  if (value == null) return 'null';
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlNum(value: number | null | undefined): string {
  return value == null ? 'null' : String(value);
}

function sqlBool(value: boolean): string {
  return value ? 'true' : 'false';
}

function sqlJson(value: unknown): string {
  if (value == null) return 'null';
  return sqlStr(JSON.stringify(value));
}

function sqlTextArray(values: string[]): string {
  return `'{${values.map((v) => `"${v.replace(/"/g, '\\"')}"`).join(',')}}'`;
}

function row(values: string[]): string {
  return `(${values.join(', ')})`;
}

function insertBlock(table: string, columns: string[], rows: string[][]): string {
  if (!rows.length) return `-- (no ${table} rows)\n`;
  const values = rows.map((r) => row(r)).join(',\n');
  return `insert into ${table} (${columns.join(', ')}) values\n${values};\n`;
}

function build(): string {
  const parts: string[] = [
    '-- AUTO-GENERATED by scripts/generate-seed-sql.ts from lib/content/*.ts.',
    '-- Do not hand-edit — run `npm run seed:generate` after changing content.',
    '--',
    '-- This reseeds content tables from scratch. It is intended for dev/staging',
    '-- databases (or a fresh `supabase db reset`); running it against a database',
    '-- with real user progress will cascade-delete attempts/submissions/bookmarks',
    '-- tied to the old content rows before the fresh rows are inserted.',
    '',
    '-- Clear existing content (children first; FKs also cascade automatically).',
    'delete from mock_sections;',
    'delete from mock_tests;',
    'delete from questions;',
    'delete from reading_passages;',
    'delete from listening_tracks;',
    'delete from writing_prompts;',
    'delete from speaking_topics;',
    'delete from lessons;',
    'delete from vocabulary_words;',
    'delete from grammar_lessons;',
    'delete from achievements;',
    '',
  ];

  parts.push('-- Lessons');
  parts.push(
    insertBlock(
      'lessons',
      ['id', 'skill', 'category', 'title', 'subtitle', 'content', 'order_index', 'is_premium', 'estimated_minutes'],
      content.lessons.map((l) => [
        sqlStr(l.id),
        sqlStr(l.skill),
        sqlStr(l.category),
        sqlStr(l.title),
        sqlStr(l.subtitle),
        sqlJson(l.content),
        sqlNum(l.orderIndex),
        sqlBool(l.isPremium),
        sqlNum(l.estimatedMinutes),
      ])
    )
  );

  parts.push('-- Reading passages');
  parts.push(
    insertBlock(
      'reading_passages',
      ['id', 'ielts_type', 'title', 'body', 'word_count', 'section_number'],
      content.readingPassages.map((p) => [sqlStr(p.id), sqlStr(p.ieltsType), sqlStr(p.title), sqlStr(p.body), sqlNum(p.wordCount), sqlNum(p.sectionNumber)])
    )
  );

  parts.push('-- Listening tracks');
  parts.push(
    insertBlock(
      'listening_tracks',
      ['id', 'title', 'transcript', 'audio_url', 'section_number'],
      content.listeningTracks.map((t) => [sqlStr(t.id), sqlStr(t.title), sqlStr(t.transcript), sqlStr(t.audioUrl), sqlNum(t.sectionNumber)])
    )
  );

  parts.push('-- Questions (reading + listening)');
  parts.push(
    insertBlock(
      'questions',
      [
        'skill', 'question_type', 'topic', 'difficulty', 'estimated_band', 'prompt', 'passage_id', 'listening_track_id',
        'options', 'correct_answer', 'explanation', 'strategy_note', 'tags', 'estimated_time_seconds', 'order_index', 'is_premium',
      ],
      content.allQuestions.map((q) => [
        sqlStr(q.skill),
        sqlStr(q.questionType),
        sqlStr(q.topic),
        sqlStr(q.difficulty),
        sqlNum(q.estimatedBand),
        sqlStr(q.prompt),
        sqlStr(q.passageId),
        sqlStr(q.listeningTrackId),
        sqlJson(q.options),
        sqlJson(q.correctAnswer),
        sqlStr(q.explanation),
        sqlStr(q.strategyNote),
        sqlTextArray(q.tags),
        sqlNum(q.estimatedTimeSeconds),
        sqlNum(q.orderIndex),
        sqlBool(q.isPremium),
      ])
    )
  );

  parts.push('-- Writing prompts');
  parts.push(
    insertBlock(
      'writing_prompts',
      ['id', 'task_type', 'ielts_type', 'title', 'prompt_text', 'category', 'chart_data', 'min_words', 'time_limit_minutes'],
      content.writingPrompts.map((p) => [
        sqlStr(p.id),
        sqlStr(p.taskType),
        sqlStr(p.ieltsType),
        sqlStr(p.title),
        sqlStr(p.promptText),
        sqlStr(p.category),
        sqlJson(p.chartData),
        sqlNum(p.minWords),
        sqlNum(p.timeLimitMinutes),
      ])
    )
  );

  parts.push('-- Speaking topics');
  parts.push(
    insertBlock(
      'speaking_topics',
      ['id', 'part', 'group_id', 'topic_category', 'cue_card_text', 'questions'],
      content.speakingTopics.map((t) => [sqlStr(t.id), sqlStr(t.part), sqlStr(t.groupId), sqlStr(t.topicCategory), sqlStr(t.cueCardText), sqlJson(t.questions)])
    )
  );

  parts.push('-- Vocabulary words');
  parts.push(
    insertBlock(
      'vocabulary_words',
      ['word', 'definition', 'example_sentence', 'topic', 'synonyms', 'collocations', 'pronunciation_ipa', 'difficulty'],
      content.vocabularyWords.map((v) => [
        sqlStr(v.word),
        sqlStr(v.definition),
        sqlStr(v.exampleSentence),
        sqlStr(v.topic),
        sqlTextArray(v.synonyms),
        sqlTextArray(v.collocations),
        sqlStr(v.pronunciationIpa),
        sqlStr(v.difficulty),
      ])
    )
  );

  parts.push('-- Grammar lessons');
  parts.push(
    insertBlock(
      'grammar_lessons',
      ['title', 'category', 'content', 'order_index'],
      content.grammarLessons.map((g) => [sqlStr(g.title), sqlStr(g.category), sqlJson(g.content), sqlNum(g.orderIndex)])
    )
  );

  parts.push('-- Achievements');
  parts.push(
    insertBlock(
      'achievements',
      ['code', 'title', 'description', 'icon', 'criteria'],
      content.achievements.map((a) => [sqlStr(a.code), sqlStr(a.title), sqlStr(a.description), sqlStr(a.icon), sqlJson(a.criteria)])
    )
  );

  parts.push('-- Mock tests');
  parts.push(
    insertBlock(
      'mock_tests',
      ['id', 'title', 'ielts_type', 'test_number', 'difficulty', 'is_free'],
      content.mockTests.map((m) => [sqlStr(m.id), sqlStr(m.title), sqlStr(m.ieltsType), sqlNum(m.testNumber), sqlStr(m.difficulty), sqlBool(m.isFree)])
    )
  );

  parts.push('-- Mock sections');
  parts.push(
    insertBlock(
      'mock_sections',
      ['mock_test_id', 'skill', 'order_index', 'duration_minutes', 'content_ref'],
      content.mockSections.map((s) => [sqlStr(s.mockTestId), sqlStr(s.skill), sqlNum(s.orderIndex), sqlNum(s.durationMinutes), sqlJson(s.contentRef)])
    )
  );

  return parts.join('\n');
}

fs.writeFileSync(OUT_PATH, build());
console.log(`Wrote ${path.relative(process.cwd(), OUT_PATH)}`);
