// Generates real listening-test audio from a configurable TTS provider.
//
//   npm run audio:generate
//
// Requires OPENAI_API_KEY in .env (a plain dev-machine secret — this is a
// one-off local script, not part of the app bundle or the server-side Edge
// Functions, so it does not use the EXPO_PUBLIC_ prefix or the Supabase
// secrets store; see supabase/functions/.env.example for the *runtime* key
// the Edge Functions use). Without it, this prints instructions and exits
// without changing anything. Every listening track already works without
// this: the app falls back to real, audible on-device text-to-speech
// (components/testing/TranscriptAudioPlayer.tsx) for any track that has no
// generated file. Running this script upgrades those tracks to pre-rendered,
// higher-quality audio.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import dotenv from 'dotenv';

import { content } from '../lib/content';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const ASSETS_DIR = path.join(ROOT, 'assets', 'audio');
const REGISTRY_PATH = path.join(ROOT, 'lib', 'content', 'audioRegistry.ts');

dotenv.config({ path: path.join(ROOT, '.env') });

const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const OPENAI_TTS_MODEL = process.env.OPENAI_TTS_MODEL || 'tts-1';
// A couple of distinct voices so multi-speaker sections (receptionist/caller,
// lecturer) don't all sound identical — assigned by track section number.
const VOICE_BY_SECTION: Record<number, string> = { 1: 'alloy', 2: 'echo', 3: 'nova', 4: 'onyx' };

async function synthesizeOpenAI(text: string, voice: string): Promise<Buffer> {
  const res = await fetch('https://api.openai.com/v1/audio/speech', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${OPENAI_API_KEY}` },
    body: JSON.stringify({ model: OPENAI_TTS_MODEL, voice, input: text, response_format: 'mp3' }),
  });
  if (!res.ok) throw new Error(`OpenAI TTS request failed: ${res.status} ${await res.text()}`);
  return Buffer.from(await res.arrayBuffer());
}

function writeRegistry(ids: string[]) {
  const lines = ids.map((id) => `  '${id}': require('../../assets/audio/${id}.mp3'),`);
  const body = `// AUTO-GENERATED by scripts/generate-audio.ts — do not hand-edit; re-run the
// script instead. Maps a listening_tracks id to a bundled local audio asset.
// Metro requires local asset paths to be static string literals, so this
// file is rewritten in full on every run and must only reference files that
// actually exist under assets/audio/.
export const audioRegistry: Record<string, number> = {
${lines.join('\n')}
};
`;
  fs.writeFileSync(REGISTRY_PATH, body);
}

async function main() {
  if (!OPENAI_API_KEY) {
    console.log('No OPENAI_API_KEY set — nothing to generate.');
    console.log('Add it to .env with a real OpenAI API key and re-run: npm run audio:generate');
    console.log('Every listening track already plays via on-device text-to-speech without this.');
    return;
  }

  fs.mkdirSync(ASSETS_DIR, { recursive: true });
  const tracks = content.listeningTracks;
  const readyIds: string[] = [];

  for (const track of tracks) {
    const filePath = path.join(ASSETS_DIR, `${track.id}.mp3`);
    if (fs.existsSync(filePath)) {
      console.log(`Already generated: ${track.title}`);
      readyIds.push(track.id);
      continue;
    }
    const voice = VOICE_BY_SECTION[track.sectionNumber] ?? 'alloy';
    console.log(`Generating "${track.title}" (section ${track.sectionNumber}, voice ${voice}, ${track.transcript.length} chars)...`);
    try {
      const audio = await synthesizeOpenAI(track.transcript, voice);
      fs.writeFileSync(filePath, audio);
      readyIds.push(track.id);
      console.log(`  Saved ${path.relative(ROOT, filePath)} (${(audio.length / 1024).toFixed(0)} KB)`);
    } catch (err) {
      console.error(`  Failed: ${(err as Error).message}`);
    }
  }

  writeRegistry(readyIds);
  console.log(`\n${readyIds.length}/${tracks.length} tracks have generated audio.`);
  console.log(`Wrote ${path.relative(ROOT, REGISTRY_PATH)}.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
